#CLI_FILENAME = nvram

LIB_VERMAJOR = 0
LIB_VERMINOR = 1
LIB_FILENAME = libsmalloc.so

LIB_CFLAGS  = $(CFLAGS) -shared -fPIC
LIB_LDFLAGS =  -Wl,-soname,$(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR)

CLI_CFLAGS  = $(CFLAGS)
CLI_LDFLAGS = $(LDFLAGS)

HEAD = $(wildcard *.h)
SOURCE = $(wildcard *.c)
OBJ = $(patsubst %.c, %.o, $(SOURCE))

all: libsmalloc

#$(OBJ): $(HEAD) $(SOURCE)
#	$(CC) $(CLI_CFLAGS) -c -o $@ $<

libsmalloc:
#	$(CC) $(LIB_CFLAGS) -c -o $(OBJ) $(SOURCE)
	$(CC) $(CLI_CFLAGS) -c -o dlmalloc.o dlmalloc.c -I ../include
	$(CC) $(LIB_CFLAGS) $(LIB_LDFLAGS) -o $(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR) $(OBJ)
	$(CC) $(LIB_CFLAGS) $(LIB_LDFLAGS) -o $(LIB_FILENAME) $(OBJ)

clean:
	rm -f $(CLI_FILENAME) $(LIB_FILENAME)* *.o

install: all
	install -D $(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR) $(ROOTFSDIR)/usr/lib/$(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR)
