#ifndef _LW_CONFIG_OID_H_
#define _LW_CONFIG_OID_H_

#ifdef  __cplusplus
extern "C"{
#endif
enum tagLW_MID_DEF
{
	CONFIG_MID_BASE=1,
    CONFIG_MID_SYSTEM,
    CONFIG_MID_NTP,
    CONFIG_MID_WEB,
    CONFIG_MID_TELNET,
    CONFIG_MID_USER,
    CONFIG_MID_ETHPORT,
    CONFIG_MID_MIRROR,
    CONFIG_MID_L2QOS,
    CONFIG_MID_VLAN,
    CONFIG_MID_MVLAN,
    CONFIG_MID_LOOP,
    CONFIG_MID_SYSLOG,
    CONFIG_MID_QOS,
    CONFIG_MID_SNMP,
	CONFIG_MID_EPON,
	CONFIG_MID_VOICEVLAN,
	CONFIG_MID_MAC_SEETING,
	CONFIG_MID_SSH,
	CONFIG_MID_CATV,
	CONFIG_MID_WLAN,
	CONFIG_MID_COMPATIBLE,
	CONFIG_MID_ANALOG,
	CONFIG_MID_ADMINGROUP,
    CONFIG_MID_MAX=255    
};

typedef enum tagCFG_DOMAIN_E
{
 CONFIG_NORMAL,
 CONFIG_FACTORY, 
 CONFIG_VIRTUAL,
 CONFIG_ATOM,
 CONFIG_MAX_DOMAINS
}CFG_DOMAIN_E;


#define CONFIG_MID_SHIFT               24
#define CONFIG_SECTION_SHIFT           19
#define CONFIG_KEY_SHIFT               14

#define CONFIG_MID(cmo)                ((cmo)&((unsigned int)0xff<<CONFIG_MID_SHIFT))
#define CONFIG_MID_SECTION(cmo)        ((cmo)&((unsigned int)0xff<<CONFIG_MID_SHIFT|(unsigned int)0x1f<<CONFIG_SECTION_SHIFT))
#define CONFIG_MID_SECTION_KEY(cmo)    ((cmo)&((unsigned int)0xff<<CONFIG_MID_SHIFT|(unsigned int)0x1f<<CONFIG_SECTION_SHIFT|(unsigned int)0x1f<<CONFIG_KEY_SHIFT))
#define CONFIG_INDEX(cmo)              ((cmo)&(0x3fff))

#define IS_ROOTCONFIG(cmo)    (0==cmo)

#define IS_MIDCONFIG(cmo)     ((0!=CONFIG_MID(cmo))&&(CONFIG_MID(cmo)==(cmo)))
#define IS_SECTIONCONFIG(_cmoid)  ((0!=CONFIG_MID(_cmoid))&&(CONFIG_MID(_cmoid)!= CONFIG_MID_SECTION(_cmoid))&&(CONFIG_MID_SECTION(_cmoid)==CONFIG_MID_SECTION_KEY(_cmoid))) 
#define IS_KEYCONFIG(_cmoid)      ((0!=CONFIG_MID(_cmoid))&&(CONFIG_MID(_cmoid)!= CONFIG_MID_SECTION(_cmoid))&&(CONFIG_MID_SECTION(_cmoid)!=CONFIG_MID_SECTION_KEY(_cmoid))) 
#define CONFIG_MAX_INDEX           (1024*16)
#define CONFIG_MIN_INDEX           0
#define CONFIG_IDX_HEXBIT          5


#define CONFIG_CMO_DEF(ModuleID, Section, Key,IDX)     (((unsigned int)(ModuleID)<<CONFIG_MID_SHIFT)|\
                                                    ((Section)<<CONFIG_SECTION_SHIFT)|((Key)<<CONFIG_KEY_SHIFT)|(IDX))
/*
#define CONFIG_BASE                                     CONFIG_CMO_DEF(CONFIG_MID_BASE,0,0,0)
#define CONFIG_SYS_(key)                                CONFIG_CMO_DEF(CONFIG_MID_BASE,1,key,0)
#define CONFIG_SYS_SECTION                              CONFIG_SYS_(0)
#define CONFIG_HEADER                                   CONFIG_SYS_(1)
#define CONFIG_VER                                      CONFIG_SYS_(2)
#define CONFIG_ID_PDTNAME                               CONFIG_SYS_(3)
#define CONFIG_ID_PASSWD                                CONFIG_SYS_(4)
#define CONFIG_SYS_PASS_TYPE                            CONFIG_SYS_(5)
#define CONFIG_L3_(Key)                                 CONFIG_CMO_DEF(CONFIG_MID_BASE,2, Key, 0)
#define CONFIG_L3_BASE                                  CONFIG_L3_(0)
#define CONFIG_DIAL_TYPE                                CONFIG_L3_(1)
#define CONFIG_IP_ADDR                                  CONFIG_L3_(2)
#define CONFIG_IP_MASK                                  CONFIG_L3_(3)
#define CONFIG_GATEWAY                                  CONFIG_L3_(4)
#define CONFIG_IP_MTU                                   CONFIG_L3_(5)
#define CONFIG_INTERVLAN_DESC                           CONFIG_L3_(6)
*/
#define CONFIG_BASE                 CONFIG_CMO_DEF(CONFIG_MID_BASE,0,0,0)
#define CONFIG_L3_(key)             CONFIG_CMO_DEF(CONFIG_MID_BASE,1,key,0)  
#define CONFIG_L3_BASE              CONFIG_L3_(0)
#define CONFIG_IP_ADDR              CONFIG_L3_(1)  
#define CONFIG_IP_MASK              CONFIG_L3_(2) 
#define CONFIG_IP_GATEWAY           CONFIG_L3_(3)
#define CONFIG_IP_MTU               CONFIG_L3_(4)  
#define CONFIG_DIAL_TYPE            CONFIG_L3_(5) 
#define CONFIG_IP_MSTDNS            CONFIG_L3_(6) 
#define CONFIG_IP_SLVDNS            CONFIG_L3_(7) 



#define CONFIG_IF_(KEY)             CONFIG_CMO_DEF(CONFIG_MID_BASE,2,KEY,0)   
#define CONFIG_IF_BASE              CONFIG_IF_(0)
#define CONFIG_IF_DESC              CONFIG_IF_(1)
#define CONFIG_IF_TYPE              CONFIG_IF_(2)
#define CONFIG_IF_NAME              CONFIG_IF_(3)
#define CONFIG_IF_ENABLE            CONFIG_IF_(4)

#define CONFIG_L2_(key)             CONFIG_CMO_DEF(CONFIG_MID_BASE,3,key,0)
#define CONFIG_L2_BASE              CONFIG_L2_(0)
#define CONFIG_PORT_SPEED           CONFIG_L2_(1)
#define CONFIG_PORT_DUPLEX          CONFIG_L2_(2)
//#define CONFIG_IF_ENABLE            CONFIG_L2_(3)


#define CONFIG_SYSTEM 				CONFIG_CMO_DEF(CONFIG_MID_SYSTEM,0,0,0)
#define CONFIG_SYS_(key)			CONFIG_CMO_DEF(CONFIG_MID_SYSTEM,1,key,0)
#define CONFIG_SYSTEM_SECTION 		CONFIG_SYS_(0)
#define CONFIG_SYSTEM_NAME 		CONFIG_SYS_(1)
//#define CONFIG_DEVICE_HWREV 		CONFIG_SYS_(2)
#define CONFIG_SUPER_PASSWORD 		CONFIG_SYS_(3)
#define CONFIG_LAN_MAC_ADDR			CONFIG_SYS_(4)


#define CONFIG_NTP 				CONFIG_CMO_DEF(CONFIG_MID_NTP,0,0,0)
#define CONFIG_NTP_(key)			CONFIG_CMO_DEF(CONFIG_MID_NTP,1,key,0)
#define CONFIG_NTP_SECTION 		CONFIG_NTP_(0)
#define CONFIG_NTP_ZONE 		CONFIG_NTP_(1)
#define CONFIG_NTP_SERVER 		CONFIG_NTP_(2)
#define CONFIG_NTP_DAYLIGHT 		CONFIG_NTP_(3)
#define CONFIG_NTP_START_M 		CONFIG_NTP_(4)
#define CONFIG_NTP_START_D 		CONFIG_NTP_(5)
#define CONFIG_NTP_TYPE 		CONFIG_NTP_(6)
#define CONFIG_NTP_SYSTIME 		CONFIG_NTP_(7)

#define CONFIG_WEB 				CONFIG_CMO_DEF(CONFIG_MID_WEB,0,0,0)
#define CONFIG_WEB_(key)			CONFIG_CMO_DEF(CONFIG_MID_WEB,1,key,0)
#define CONFIG_WEB_SECTION 		CONFIG_WEB_(0)
#define CONFIG_WEB_AUX_ENABLE 		CONFIG_WEB_(1)
#define CONFIG_WEB_USERNAME 		CONFIG_WEB_(2)
#define CONFIG_WEB_PASSWORD 		CONFIG_WEB_(3)
#define CONFIG_WEB_IDLETIME 		CONFIG_WEB_(4)
#define CONFIG_WEB_SSL_ENABLE 		CONFIG_WEB_(5)

#define CONFIG_TELNET 				CONFIG_CMO_DEF(CONFIG_MID_TELNET,0,0,0)
#define CONFIG_TELNET_(key)			CONFIG_CMO_DEF(CONFIG_MID_TELNET,1,key,0)
#define CONFIG_TELNET_SECTION 		CONFIG_TELNET_(0)
#define CONFIG_TELNET_SERVICE_ENABLE 		CONFIG_TELNET_(1)
//#define CONFIG_TELNET_ENABLE 		CONFIG_TELNET_(1)
#define CONFIG_TELNET_PORT 			CONFIG_TELNET_(2)

#define CONFIG_SSH 					CONFIG_CMO_DEF(CONFIG_MID_SSH,0,0,0)
#define CONFIG_SSH_(key)			CONFIG_CMO_DEF(CONFIG_MID_SSH,1,key,0)
#define CONFIG_SSH_SECTION 			CONFIG_SSH_(0)
#define CONFIG_SSH_SERVICE_ENABLE 	CONFIG_SSH_(1)
#define CONFIG_SSH_PORT 			CONFIG_SSH_(2)


#define CONFIG_USER 				CONFIG_CMO_DEF(CONFIG_MID_USER,0,0,0)
#define CONFIG_USER_VTY_(key)			CONFIG_CMO_DEF(CONFIG_MID_USER,1,key,0)
#define CONFIG_USER_VTY_SECTION 		CONFIG_USER_VTY_(0)
#define CONFIG_USER_VTY_NAME 		CONFIG_USER_VTY_(1)
#define CONFIG_USER_VTY_PASSWORD 		CONFIG_USER_VTY_(2)
#define CONFIG_USER_VTY_PASSWORD_TYPE 			CONFIG_USER_VTY_(3)
#define CONFIG_USER_VTY_AUTHMODE 		CONFIG_USER_VTY_(4)
#define CONFIG_USER_VTY_TIMEOUT 			CONFIG_USER_VTY_(5)

#define CONFIG_USER_WEB_(key)			CONFIG_CMO_DEF(CONFIG_MID_USER,2,key,0)
#define CONFIG_USER_WEB_SECTION 		CONFIG_USER_WEB_(0)
#define CONFIG_USER_WEB_NAME 		CONFIG_USER_WEB_(1)
#define CONFIG_USER_WEB_PASSWORD 		CONFIG_USER_WEB_(2)
#define CONFIG_USER_WEB_LEVEL 			CONFIG_USER_WEB_(3)
#if 0
#define CONFIG_ETHPORT 				CONFIG_CMO_DEF(CONFIG_MID_ETHPORT,0,0,0)
#define CONFIG_ETHPORT_(key)		CONFIG_CMO_DEF(CONFIG_MID_ETHPORT,1,key,0)
#define CONFIG_ETHPORT_SECTION 		CONFIG_ETHPORT_(0)
#define CONFIG_ETHPORT_ENABLED 		CONFIG_ETHPORT_(1)
#define CONFIG_ETHPORT_AUTONEG 		CONFIG_ETHPORT_(2)
#define CONFIG_ETHPORT_SPD 			CONFIG_ETHPORT_(3)
#define CONFIG_ETHPORT_DUP 		    CONFIG_ETHPORT_(4)
#define CONFIG_ETHPORT_PRI 			CONFIG_ETHPORT_(5)
#define CONFIG_ETHPORT_FLC 		    CONFIG_ETHPORT_(6)
#define CONFIG_ETHPORT_INGRESS_LIMIT 		CONFIG_ETHPORT_(7)
#define CONFIG_ETHPORT_ENGRESS_LIMIT 		CONFIG_ETHPORT_(8)
#define CONFIG_ETHPORT_VLANMODE 			CONFIG_ETHPORT_(9)
#define CONFIG_ETHPORT_PVID 		CONFIG_ETHPORT_(10)
#define CONFIG_ETHPORT_LINKTYPE 			CONFIG_ETHPORT_(11)
#define CONFIG_ETHPORT_LINK_TRUNK_PERMIT 			CONFIG_ETHPORT_(12)
#define CONFIG_ETHPORT_LINK_HYBRID_TAG 		CONFIG_ETHPORT_(13)
#define CONFIG_ETHPORT_LINK_HYBRID_UNTAG 			CONFIG_ETHPORT_(14)
#endif

#define CONFIG_VLAN_(Section, Key)                      CONFIG_CMO_DEF(CONFIG_MID_VLAN, Section, Key, 0)
#define CONFIG_VLAN                                        CONFIG_VLAN_(0, 0)

#define CONFIG_VLAN_INFO_SECTION                        	CONFIG_VLAN_(1, 0)
#define CONFIG_VLAN_MODE                              		CONFIG_VLAN_(1, 1)
#define CONFIG_PORTVLAN_TABLE                              	CONFIG_VLAN_(2, 0)
#define CONFIG_PORT_PVID_ETH								CONFIG_VLAN_(2, 1)
#define CONFIG_PORT_PVID_CAB                              	CONFIG_VLAN_(2, 2)
#define CONFIG_PORT_LINKTYPE_ETH							CONFIG_VLAN_(2, 3)
#define CONFIG_PORT_LINKTYPE_CAB                            CONFIG_VLAN_(2, 4)
#define CONFIG_PORT_TRUNK_PERMIT_ETH						CONFIG_VLAN_(2, 5)
#define CONFIG_PORT_TRUNK_PERMIT_CAB                        CONFIG_VLAN_(2, 6)
#define CONFIG_PORT_LINK_HYBRID_TAG_ETH						CONFIG_VLAN_(2, 7)
#define CONFIG_PORT_LINK_HYBRID_TAG_CAB						CONFIG_VLAN_(2, 8)
#define CONFIG_PORT_LINK_HYBRID_UNTAG_ETH                   CONFIG_VLAN_(2, 9)
#define CONFIG_PORT_LINK_HYBRID_UNTAG_CAB					CONFIG_VLAN_(2, 10)

#define CONFIG_PVLAN_TABLE                              CONFIG_VLAN_(3, 0)
#define CONFIG_PVLAN_TABLE_ID                           CONFIG_VLAN_(3, 1)
#define CONFIG_PVLAN_TABLE_PORT                         CONFIG_VLAN_(3, 2)

#define CONFIG_VLANGROUP_TABLE                            CONFIG_VLAN_(4, 0)
#define CONFIG_VLANGROUP                                  CONFIG_VLAN_(4, 1)



#define CONFIG_MVLAN 				CONFIG_CMO_DEF(CONFIG_MID_MVLAN,0,0,0)
#define CONFIG_MVLAN_(key)			CONFIG_CMO_DEF(CONFIG_MID_MVLAN,1,key,0)
#define CONFIG_MVLAN_SECTION 		CONFIG_MVLAN_(0)
#define CONFIG_MVLAN_VID 		    CONFIG_MVLAN_(1)
#define CONFIG_MVLAN_INTERFACE 		CONFIG_MVLAN_(2)
#define CONFIG_LOOP 				CONFIG_CMO_DEF(CONFIG_MID_LOOP,0,0,0)
#define CONFIG_LOOP_(key)			CONFIG_CMO_DEF(CONFIG_MID_LOOP,1,key,0)
#define CONFIG_LOOP_SECTION 		CONFIG_LOOP_(0)
#define CONFIG_LOOP_ENABLED 		CONFIG_LOOP_(1)
#define CONFIG_LOOP_UPDATE 		    CONFIG_LOOP_(2)
/*Begin add by linguobin 2013-9-5*/
#define CONFIG_VOICEVLAN 				CONFIG_CMO_DEF(CONFIG_MID_VOICEVLAN,0,0,0)
#define CONFIG_VOICEVLAN_(key)			CONFIG_CMO_DEF(CONFIG_MID_VOICEVLAN,1,key,0)
#define CONFIG_VOICEVLAN_SECTION 		CONFIG_VOICEVLAN_(0)
#define CONFIG_VOICEVLAN_VID 		    CONFIG_VOICEVLAN_(1)
#define CONFIG_VOICEVLAN_ENABLE 		CONFIG_VOICEVLAN_(2)
#define CONFIG_VOICEVLAN_MODE 		    CONFIG_VOICEVLAN_(3)

#define CONFIG_PORT_(key)			    CONFIG_CMO_DEF(CONFIG_MID_VOICEVLAN,2,key,0)
#define CONFIG_PORT_SECTION 		    CONFIG_PORT_(0)
#define CONFIG_PORT_ENABLE 		        CONFIG_PORT_(1)

#define CONFIG_OUI_(key)			    CONFIG_CMO_DEF(CONFIG_MID_VOICEVLAN,3,key,0)
#define CONFIG_OUI_SECTION 		        CONFIG_OUI_(0)
#define CONFIG_OUI_ADDR 		        CONFIG_OUI_(1)
#define CONFIG_OUI_NAME 		        CONFIG_OUI_(2)
#define CONFIG_OUI_MASK 		        CONFIG_OUI_(3)

/*End add by linguobin 2013-9-5*/

#define CONFIG_SYSLOG 				CONFIG_CMO_DEF(CONFIG_MID_SYSLOG,0,0,0)
#define CONFIG_SYSLOG_(key)			CONFIG_CMO_DEF(CONFIG_MID_SYSLOG,1,key,0)
#define CONFIG_SYSLOG_SECTION 		CONFIG_SYSLOG_(0)
#define CONFIG_SYSLOG_ENABLED 		CONFIG_SYSLOG_(1)
#define CONFIG_SYSLOG_IP    		CONFIG_SYSLOG_(2)
#define CONFIG_SYSLOG_DEGREE   		CONFIG_SYSLOG_(3)
#define CONFIG_SYSLOG_SAVE_DEGREE	CONFIG_SYSLOG_(4)
#define CONFIG_SYSLOG_PORT			CONFIG_SYSLOG_(5)


#define CONFIG_QOS_(Section, Key)                CONFIG_CMO_DEF(CONFIG_MID_QOS, Section, Key, 0)
#define CONFIG_QOS                               CONFIG_QOS_(0, 0)
#define CONFIG_QOS_QOSMODE_SECTION               CONFIG_QOS_(1, 0)
#define CONFIG_QOS_MODE                          CONFIG_QOS_(1, 1)
#define CONFIG_QOS_QUEUEMODE_SECTION             CONFIG_QOS_(2, 0)
#define CONFIG_QOS_QUEUEMODE					 CONFIG_QOS_(2, 1)
#define CONFIG_QOS_WEIGHT_TABLE                  CONFIG_QOS_(3, 0)
#define CONFIG_QOS_WEIGHT					     CONFIG_QOS_(3, 1)


#define CONFIG_ETHPORT 				        CONFIG_CMO_DEF(CONFIG_MID_ETHPORT,0,0,0)
#define CONFIG_ETHPORT_(key)		      	CONFIG_CMO_DEF(CONFIG_MID_ETHPORT,1,key,0)
#define CONFIG_ETHPORT_SECTION 				CONFIG_ETHPORT_(0)
#define CONFIG_ETHPORT_DESCRIPTION  		CONFIG_ETHPORT_(1)
#define CONFIG_ETHPORT_ENABLED 				CONFIG_ETHPORT_(2)
#define CONFIG_ETHPORT_SPD 					CONFIG_ETHPORT_(3)
#define CONFIG_ETHPORT_DUP 		    		CONFIG_ETHPORT_(4)
#define CONFIG_ETHPORT_PRI 					CONFIG_ETHPORT_(5)
#define CONFIG_ETHPORT_FC 		    		CONFIG_ETHPORT_(6)
#define CONFIG_ETHPORT_MDIX 				CONFIG_ETHPORT_(7)
#define CONFIG_ETHPORT_ISOLATE 				CONFIG_ETHPORT_(8)
#define CONFIG_ETHPORT_INRATE 				CONFIG_ETHPORT_(9)
#define CONFIG_ETHPORT_OUTRATE 				CONFIG_ETHPORT_(10)
#define CONFIG_ETHPORT_MIRRORMOD 			CONFIG_ETHPORT_(11)
#define CONFIG_ETHPORT_UCAST_STORMCTL_EN    CONFIG_ETHPORT_(12)
#define CONFIG_ETHPORT_MCAST_STORMCTL_EN	CONFIG_ETHPORT_(13)
#define CONFIG_ETHPORT_BCAST_STORMCTL_EN    CONFIG_ETHPORT_(14)
#define CONFIG_ETHPORT_STORMCTL_PERCENT     CONFIG_ETHPORT_(15)




#define CONFIG_SNMP 				    CONFIG_CMO_DEF(CONFIG_MID_SNMP,0,0,0)
#define CONFIG_SNMP_(key)			    CONFIG_CMO_DEF(CONFIG_MID_SNMP,1,key,0)
#define CONFIG_SNMP_SECTION             CONFIG_SNMP_(0)
#define CONFIG_SNMP_ENABLED  		    CONFIG_SNMP_(1)
#define CONFIG_SNMP_ENGINEID 		    CONFIG_SNMP_(2)
#define CONFIG_SNMP_MAX_PACKET_LEN      CONFIG_SNMP_(3)
#define CONFIG_SNMP_LOCATION            CONFIG_SNMP_(4)
#define CONFIG_SNMP_CONTACT             CONFIG_SNMP_(5)
#define CONFIG_SNMP_VERSION             CONFIG_SNMP_(6)
#define CONFIG_SNMP_TRUST_HOST          CONFIG_SNMP_(7)
#define CONFIG_SNMP_COMM_CURRENT_COUNT  CONFIG_SNMP_(8)
#define CONFIG_SNMP_GROUP_CURRENT_COUNT CONFIG_SNMP_(9)
#define CONFIG_SNMP_TRAP_EN             CONFIG_SNMP_(10)
#define CONFIG_SNMP_TRAP_IP             CONFIG_SNMP_(11)
#define CONFIG_SNMP_TRAP_COM            CONFIG_SNMP_(12)
#define CONFIG_SNMP_TRAP_COMMUNITY      CONFIG_SNMP_(13)
#define CONFIG_SNMP_TRAP_VERSION        CONFIG_SNMP_(14)
#define CONFIG_SNMP_TRAP_SAFE           CONFIG_SNMP_(15)
#define CONFIG_SNMP_LAST_SAVE_SAFE_NUM  CONFIG_SNMP_(16)
#define CONFIG_SNMP_USER_CURRENT_COUNT  CONFIG_SNMP_(17)


#define CONFIG_SNMP_COMMUNITIES_(key)	CONFIG_CMO_DEF(CONFIG_MID_SNMP,2,key,0)
#define CONFIG_SNMP_COMMUNITIES_SECTION CONFIG_SNMP_COMMUNITIES_(0)
#define CONFIG_SNMP_COMM_NAME           CONFIG_SNMP_COMMUNITIES_(1)
#define CONFIG_SNMP_ACCESS_MODE         CONFIG_SNMP_COMMUNITIES_(2)

#define CONFIG_SNMP_GROUP_(key)	        CONFIG_CMO_DEF(CONFIG_MID_SNMP,3,key,0)
#define CONFIG_SNMP_GROUP_SECTION       CONFIG_SNMP_GROUP_(0)
#define CONFIG_SNMP_GROUP_NAME          CONFIG_SNMP_GROUP_(1)
#define CONFIG_SNMP_GROUP_SECURITY      CONFIG_SNMP_GROUP_(2)
#define CONFIG_SNMP_GROUP_MODE          CONFIG_SNMP_GROUP_(3)

#define CONFIG_SNMP_USER_(key)	        CONFIG_CMO_DEF(CONFIG_MID_SNMP,4,key,0)
#define CONFIG_SNMP_USER_SECTION        CONFIG_SNMP_USER_(0)
#define CONFIG_SNMP_USER_NMAE           CONFIG_SNMP_USER_(1)
#define CONFIG_SNMP_USER_GROUP          CONFIG_SNMP_USER_(2)
#define CONFIG_SNMP_SECURITY            CONFIG_SNMP_USER_(3)
#define CONFIG_SNMP_PASSWORD            CONFIG_SNMP_USER_(4)
#define CONFIG_SNMP_ENPASSWORD          CONFIG_SNMP_USER_(5)

#define CONFIG_EPON 				CONFIG_CMO_DEF(CONFIG_MID_EPON,0,0,0)
#define CONFIG_EPON_(key)			CONFIG_CMO_DEF(CONFIG_MID_EPON,1,key,0)
#define CONFIG_EPON_SECTION 		CONFIG_EPON_(0)
#define CONFIG_EPON_LOID			CONFIG_EPON_(1)
#define CONFIG_EPON_PASSWD    		CONFIG_EPON_(2)

#define CONFIG_MAC_SEETING 							CONFIG_CMO_DEF(CONFIG_MID_MAC_SEETING, 0, 0, 0)
#define CONFIG_MAC_SEETING_(key)					CONFIG_CMO_DEF(CONFIG_MID_MAC_SEETING, 1, key, 0)
#define CONFIG_MAC_SEETING_SECTION 					CONFIG_MAC_SEETING_(0)
#define CONFIG_MAC_SEETING_AGING_TIME				CONFIG_MAC_SEETING_(1)


#define CONFIG_CATV 				    			CONFIG_CMO_DEF(CONFIG_MID_CATV,0,0,0)
#define CONFIG_CATV_(key)			    			CONFIG_CMO_DEF(CONFIG_MID_CATV,1,key,0)
#define CONFIG_CATV_SECTION           				CONFIG_CATV_(0)
#define CONFIG_CATV_UPDATE           				CONFIG_CATV_(1)
#define CONFIG_CATV_OUTPUT_LEVEL_ATTEN  		    CONFIG_CATV_(2)

#define CONFIG_WLAN 				    			CONFIG_CMO_DEF(CONFIG_MID_WLAN,0,0,0)
#define CONFIG_WLAN_(key)			    			CONFIG_CMO_DEF(CONFIG_MID_WLAN,1,key,0)
#define CONFIG_WLAN_SECTION           				CONFIG_WLAN_(0)
#define CONFIG_WLAN_ENABLED  		    			CONFIG_WLAN_(1)
#define CONFIG_WLAN_MODEL  		    				CONFIG_WLAN_(2)
#define CONFIG_WLAN_BANDWIDTH  		    			CONFIG_WLAN_(3)
#define CONFIG_WLAN_CHANNEL  		    			CONFIG_WLAN_(4)
#define CONFIG_WLAN_TX_RATE  		    			CONFIG_WLAN_(5)
#define CONFIG_WLAN_MAC_FILTER_EN  		    		CONFIG_WLAN_(6)
#define CONFIG_WLAN_MAC_FILTER_MODEL  		    	CONFIG_WLAN_(7)
#define CONFIG_WLAN_BEACON_INTERVAL  		    	CONFIG_WLAN_(8)
#define CONFIG_WLAN_RST_THRESHOLD  		    		CONFIG_WLAN_(9)
#define CONFIG_WLAN_FRAG  		    				CONFIG_WLAN_(10)
#define CONFIG_WLAN_DTIM_INTERVAL  		    		CONFIG_WLAN_(11)
#define CONFIG_WLAN_TXPOWER  		    			CONFIG_WLAN_(12)
#define CONFIG_WLAN_WMM_EN  		    			CONFIG_WLAN_(13)
#define CONFIG_WLAN_UP_SER_VLAN  		    		CONFIG_WLAN_(14)
#define CONFIG_WLAN_SSID_(key)						CONFIG_CMO_DEF(CONFIG_MID_WLAN,2,key,0)
#define CONFIG_WLAN_SSID_SECTION 					CONFIG_WLAN_SSID_(0)
#define CONFIG_WLAN_SSID_NAME           			CONFIG_WLAN_SSID_(1)
#define CONFIG_WLAN_SSID_EN         				CONFIG_WLAN_SSID_(2)
#define CONFIG_WLAN_SSID_ISOLATE_EN         		CONFIG_WLAN_SSID_(3)
#define CONFIG_WLAN_SSID_BCAST_EN         			CONFIG_WLAN_SSID_(4)
#define CONFIG_WLAN_AUTHTYPE  		    			CONFIG_WLAN_SSID_(5)
#define CONFIG_WLAN_SSID_ENC_TYPE       			CONFIG_WLAN_SSID_(6)
#define CONFIG_WLAN_SSID_ENC_WEP_GROUP      		CONFIG_WLAN_SSID_(7)
#define CONFIG_WLAN_SSID_ENC_WEP_KEY_LEN    		CONFIG_WLAN_SSID_(8)
#define CONFIG_WLAN_SSID_ENC_WEP_KEY_TYPE   		CONFIG_WLAN_SSID_(9)
#define CONFIG_WLAN_SSID_ENC_WEP_KEY   				CONFIG_WLAN_SSID_(10)
#define CONFIG_WLAN_SSID_ENC_WPA_KEY   				CONFIG_WLAN_SSID_(11)
#define CONFIG_WLAN_SSID_ENC_WPA_KEY_TYPE   		CONFIG_WLAN_SSID_(12)
#define CONFIG_WLAN_SSID_ENC_WPA_KEY_PERIOD   		CONFIG_WLAN_SSID_(13)
#define CONFIG_WLAN_FILTER_MAC_(key)				CONFIG_CMO_DEF(CONFIG_MID_WLAN,3,key,0)
#define CONFIG_WLAN_FILTER_MAC_SECTION 				CONFIG_WLAN_FILTER_MAC_(0)
#define CONFIG_WLAN_FILTER_MAC_MAC           		CONFIG_WLAN_FILTER_MAC_(1)
#define CONFIG_WLAN_FILTER_MAC_MAC_DEC           	CONFIG_WLAN_FILTER_MAC_(2)

#define CONFIG_COMPATIBLE 				    		CONFIG_CMO_DEF(CONFIG_MID_COMPATIBLE,0,0,0)
#define CONFIG_COMPATIBLE_(key)			    		CONFIG_CMO_DEF(CONFIG_MID_COMPATIBLE,1,key,0)
#define CONFIG_COMPATIBLE_SECTION           		CONFIG_COMPATIBLE_(0)
#define CONFIG_COMPATIBLE_MODE           			CONFIG_COMPATIBLE_(1)

#define CONFIG_ANALOG_PROPERTY 				   		CONFIG_CMO_DEF(CONFIG_MID_ANALOG,0,0,0)
#define CONFIG_ANALOG_PROPERTY_(key)			    CONFIG_CMO_DEF(CONFIG_MID_ANALOG,1,key,0)
#define CONFIG_ANALOG_PROPERTY_SECTION              CONFIG_ANALOG_PROPERTY_(0)
#define CONFIG_ANALOG_PROPERTY_ENABLED  		    CONFIG_ANALOG_PROPERTY_(1)
#define CONFIG_ANALOG_PROPERTY_HIHI 		        CONFIG_ANALOG_PROPERTY_(2)
#define CONFIG_ANALOG_PROPERTY_HI       		    CONFIG_ANALOG_PROPERTY_(3)
#define CONFIG_ANALOG_PROPERTY_LO            		CONFIG_ANALOG_PROPERTY_(4)
#define CONFIG_ANALOG_PROPERTY_LOLO		            CONFIG_ANALOG_PROPERTY_(5)
#define CONFIG_ANALOG_PROPERTY_DEADBAND             CONFIG_ANALOG_PROPERTY_(6)

#define CONFIG_AdminGroup 				    		CONFIG_CMO_DEF(CONFIG_MID_ADMINGROUP,0,0,0)
#define CONFIG_AdminGroup_(key)			    		CONFIG_CMO_DEF(CONFIG_MID_ADMINGROUP,1,key,0)
#define CONFIG_AdminGroup_SECTION           		CONFIG_AdminGroup_(0)
#define CONFIG_AdminGroup_NELogicalID           	CONFIG_AdminGroup_(1)
#define CONFIG_AdminGroup_CheckCode           		CONFIG_AdminGroup_(2)
#define CONFIG_AdminGroup_TrapCommunity           	CONFIG_AdminGroup_(3)

































/***register info **************/
#define CONFIG_PLAT_OIDTABLE \
{CONFIG_SYSTEM, "system", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SYSTEM_SECTION, "system_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SYSTEM_NAME, "sys_systemname", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SUPER_PASSWORD, "super_password", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_LAN_MAC_ADDR, "sys_mac", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP, "ntp", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_SECTION, "ntp_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_ZONE, "ntp_time_zone", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_NTP_SERVER, "ntp_time_server", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_DAYLIGHT, "ntp_daylight", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_START_M, "ntp_dl_start_m", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_START_D, "ntp_dl_start_d", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_TYPE, "ntp_type", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_NTP_SYSTIME, "ntp_systime", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB, "web", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_SECTION, "web_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_AUX_ENABLE, "web_aux_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_USERNAME, "web_username_aux", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_PASSWORD, "web_password_aux", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_IDLETIME, "web_idle_time", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WEB_SSL_ENABLE, "web_ssl_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_TELNET, "telnet", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_TELNET_SECTION, "telnet_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_TELNET_SERVICE_ENABLE, "telnet_service_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_TELNET_PORT, "sys_telnet_port", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER, "user", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_SECTION, "vty_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_NAME, "user_vty_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_PASSWORD, "user_vty_password", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_PASSWORD_TYPE, "user_vty_password_type", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_AUTHMODE, "user_vty_authmode", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_VTY_TIMEOUT, "user_vty_timeout", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_USER_WEB_SECTION, "web_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_WEB_NAME, "user_web_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_WEB_PASSWORD, "user_web_password", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_USER_WEB_LEVEL, "user_web_level", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_BASE,"base",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR}, \
{CONFIG_L3_BASE,"l3base",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},  \
{CONFIG_IP_ADDR,"ipaddress",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR}, \
{CONFIG_IP_MTU,"mtu",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IP_GATEWAY,"gateway",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IP_MASK,"ipmask",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},  \
{CONFIG_DIAL_TYPE,"dialtype",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IP_SLVDNS,"slavedns",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IF_BASE,"ifbase",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IF_DESC,"ifdescription",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IF_TYPE,"iftype",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IF_NAME,"ifname",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_IF_ENABLE,"ifenable",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_L2_BASE,"l2base",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_PORT_SPEED,"portspeed",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_PORT_DUPLEX,"portduplex",0,0,0,CFG_OID_TYPE_SINGLE,NULL,CFG_TYPE_STR},\
{CONFIG_LOOP, "loop", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_LOOP_SECTION, "loop_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_LOOP_ENABLED, "loop_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_LOOP_UPDATE, "loop_update", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_VLAN,"vlan",0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_VLAN_INFO_SECTION,"vlanmodesection",0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_VLAN_MODE,"vlanmode",0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORTVLAN_TABLE,"vlanporttable",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORT_PVID_ETH,"vlanportpvid",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORT_LINKTYPE_ETH,"vlanporttype",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORT_TRUNK_PERMIT_ETH,"vlanporttrunk",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORT_LINK_HYBRID_TAG_ETH,"vlanporthybridtag",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_PORT_LINK_HYBRID_UNTAG_ETH,"vlanporthybriduntag",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_VLANGROUP_TABLE, "vlangrouptable", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_VLANGROUP, "vlangroup", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_MVLAN, "mvlan", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_MVLAN_SECTION, "mvlan_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_MVLAN_VID, "vlan_manage_vid", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_MVLAN_INTERFACE, "vlan_interface", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SYSLOG, "syslog", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SYSLOG_SECTION, "syslog_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SYSLOG_ENABLED, "syslog_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SYSLOG_IP, "syslog_ip", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SYSLOG_DEGREE, "syslog_degree", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SYSLOG_SAVE_DEGREE, "syslog_save_degree", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SYSLOG_PORT, "syslog_port", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_EPON, "epon", 0,0,1, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_EPON_SECTION, "epon_info", 0,0,1, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_EPON_LOID, "epon_loid", 0,0,1, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_EPON_PASSWD, "epon_passwd", 0,0,1, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS, "qos", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_QOSMODE_SECTION, "qos_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_MODE, "qos_qosmode", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_QUEUEMODE_SECTION, "qos_queue_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_QUEUEMODE, "qos_queuemode", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_WEIGHT_TABLE,"qos_weight_table",0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_QOS_WEIGHT, "qos_weight", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_ETHPORT, "ethport", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_SECTION,"ethport_table",0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_DESCRIPTION, "ethport_description", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_ENABLED, "ethport_enable", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_SPD, "ethport_speed", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_DUP, "ethport_duplex", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_PRI, "ethport_priority", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_ETHPORT_FC, "ethport_flowcontrl", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_MDIX, "ethport_mdix", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_ISOLATE, "ethport_isolate", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_INRATE, "ethport_inlimit", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_OUTRATE, "ethport_outlimit", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_MIRRORMOD, "ethport_mirror", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_UCAST_STORMCTL_EN, "ethport_stormctl_ucast_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_MCAST_STORMCTL_EN, "ethport_stormctl_mcast_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_BCAST_STORMCTL_EN, "ethport_stormctl_bcast_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ETHPORT_STORMCTL_PERCENT, "ethport_stormctl_percent", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP, "snmp", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_SECTION, "snmp_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_ENABLED, "snmp_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_ENGINEID, "snmp_engineID", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_MAX_PACKET_LEN, "snmp_max_packet_len", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_LOCATION, "snmp_location", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_CONTACT, "snmp_contact", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_VERSION, "snmp_version", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_TRUST_HOST, "snmp_trust_host", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_COMM_CURRENT_COUNT, "snmp_comm_current_count", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_GROUP_CURRENT_COUNT, "snmp_group_current_count", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_TRAP_EN, "snmp_trap_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_TRAP_IP, "snmp_trap_ip", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_TRAP_COM, "snmp_trap_com", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_TRAP_COMMUNITY, "snmp_trap_community", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_TRAP_VERSION, "snmp_trap_version", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_TRAP_SAFE, "snmp_trap_safe", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_LAST_SAVE_SAFE_NUM, "snmp_last_save_safe_num", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_USER_CURRENT_COUNT, "snmp_user_current_count", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SNMP_COMMUNITIES_SECTION, "communities_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_COMM_NAME, "snmp_comm_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_ACCESS_MODE, "snmp_access_mode", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_GROUP_SECTION, "group_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_GROUP_NAME, "snmp_group_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_GROUP_SECURITY, "snmp_group_security", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_GROUP_MODE, "snmp_group_mode", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_USER_SECTION, "user_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_USER_NMAE, "snmp_user_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_USER_GROUP, "snmp_user_group", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_SECURITY, "snmp_user_security", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_PASSWORD, "snmp_user_password", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_ENPASSWORD, "snmp_user_enpassword", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_VOICEVLAN, "voice_vlan", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_VOICEVLAN_SECTION, "voice_vlan_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_VOICEVLAN_VID, "voice_vlan_id", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_VOICEVLAN_ENABLE, "voice_vlan_enable", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_VOICEVLAN_MODE, "voice_vlan_mode", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_PORT_SECTION, "port_voice_vlan_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\    
{CONFIG_PORT_ENABLE, "port_voice_vlan_enable", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_OUI_SECTION, "voice_vlan_oui_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_OUI_ADDR, "voice_vlan_oui_addr", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_OUI_NAME, "voice_vlan_oui_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_OUI_MASK, "voice_vlan_oui_mask", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_SNMP_ENPASSWORD, "snmp_user_enpassword", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_MAC_SEETING, "mac_setting", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_MAC_SEETING_SECTION, "mac_setting_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_MAC_SEETING_AGING_TIME, "mac_setting_aging_time", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_SSH, "ssh", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SSH_SECTION, "ssh_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SSH_SERVICE_ENABLE, "ssh_service_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_SSH_PORT, "ssh_port", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN, "wlan", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SECTION, "wlan_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_ENABLED, "wlan_enabled", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_MODEL, "wlan_model", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_BANDWIDTH, "wlan_bandwidth", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_CHANNEL, "wlan_channel", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_TX_RATE, "wlan_tx_rate", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_MAC_FILTER_EN, "wlan_mac_filter_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_MAC_FILTER_MODEL, "wlan_mac_filter_model", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_BEACON_INTERVAL, "wlan_beacon_interval", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_RST_THRESHOLD, "wlan_rst_threshold", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_FRAG, "wlan_frag", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_DTIM_INTERVAL, "wlan_dtim_interval", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_TXPOWER, "wlan_txpower", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_WMM_EN, "wlan_wmm_en", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_UP_SER_VLAN, "wlan_up_ser_vlan", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_SSID_SECTION, "wlan_ssid_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_NAME, "wlan_ssid_name", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_EN, "wlan_ssid_en", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ISOLATE_EN, "wlan_ssid_isolate_en", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_BCAST_EN, "wlan_ssid_bcast_en", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_AUTHTYPE, "wlan_authtype", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_TYPE, "wlan_ssid_enc_type", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WEP_GROUP, "wlan_ssid_enc_wep_group", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_SSID_ENC_WEP_KEY_LEN, "wlan_ssid_enc_wep_key_len", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WEP_KEY_TYPE, "wlan_ssid_enc_wep_key_type", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WEP_KEY, "wlan_ssid_enc_wep_key", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WPA_KEY, "wlan_ssid_enc_wpa_key", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WPA_KEY_TYPE, "wlan_ssid_enc_wpa_key_type", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_SSID_ENC_WPA_KEY_PERIOD, "wlan_ssid_enc_wpa_key_period", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_WLAN_FILTER_MAC_SECTION, "wlan_mac_filter_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_FILTER_MAC_MAC, "wlan_mac_filter_mac", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_WLAN_FILTER_MAC_MAC_DEC, "wlan_mac_filter_dec", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_CATV, "catv", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_CATV_SECTION, "catv_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_CATV_UPDATE, "update", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_COMPATIBLE, "compatible", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_COMPATIBLE_SECTION, "compatible_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_COMPATIBLE_MODE, "compatible_mode", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_CATV_OUTPUT_LEVEL_ATTEN, "output_level_atten", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_ANALOG_PROPERTY, "analog_property_table", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_ANALOG_PROPERTY_SECTION, "analog_property_", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_ANALOG_PROPERTY_ENABLED, "analog_alarm_enable", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_STR},\
{CONFIG_ANALOG_PROPERTY_HIHI, "analog_alarm_hihi", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_ANALOG_PROPERTY_HI, "analog_alarm_hi", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_ANALOG_PROPERTY_LO, "analog_alarm_lo", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_ANALOG_PROPERTY_LOLO, "analog_alarm_lolo", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_ANALOG_PROPERTY_DEADBAND, "analog_alarm_deadband", 0,0,0, CFG_OID_TYPE_TABLE, NULL, CFG_TYPE_INT},\
{CONFIG_AdminGroup, "commonAdminGroup", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_AdminGroup_SECTION, "commonAdminGroup_info", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_AdminGroup_NELogicalID, "commonNELogicalID", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR},\
{CONFIG_AdminGroup_CheckCode, "commonCheckCode", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_INT},\
{CONFIG_AdminGroup_TrapCommunity, "commonTrapCommunityString", 0,0,0, CFG_OID_TYPE_SINGLE, NULL, CFG_TYPE_STR}









#define DEFAULT_TELNET_SERVICE_STR "enable"
#define DEFAULT_MANAGEMENT_VLAN_STR "1"
#define DEFAULT_LOOPBACK_ENABLE_STR "disable"

#define DEFAULT_SYSLOG_ENABLE_STR "0"
#define DEFAULT_SYSLOG_DEGREE_STR "5"
#define DEFAULT_SYSLOG_SAVEDEGREE_STR "7"
#define DEFAULT_SYSLOG_IP_STR "0.0.0.0"





#ifdef  __cplusplus
}
#endif
#endif

