PWD := $(shell /bin/pwd)
#MODULE_DIR := /home/hxu/work/linux-module/opl_linux_module
MODULE_DIR := ..
obj-m := opl_minte.o 

#opl_minte-objs += opl_minte.o
#opl_minte-objs += ipmux_interrupt.o

MODULE_NAME := opl_minte.ko

include $(DRV_BASE_DIR)/build/Makefile.conf

