#ifndef __RCM_CUSTOMIZE_H
#define __RCM_CUSTOMIZE_H

#undef CONFIG_RTK_VOIP_G7231
#undef CONFIG_RTK_VOIP_RTK_VOIP_SPEEX_NB
#undef CONFIG_RTK_VOIP_G726
#undef CONFIG_RTK_VOIP_GSMFR
#undef CONFIG_RTK_VOIP_ILBC
#undef CONFIG_RTK_VOIP_G722

#endif
