all:
	cp ../opl_minte/*.[ch] ./
	cp ../opl_minte/test/*.[ch] ./
	cp ../opl_cpuif/*.[ch] ./
	cp ../opl_cpuif/test/*.[ch] ./
	cp ../opl_reg/*.[ch] ./
	cp ../opl_reg/test/*.[ch] ./
	cp ../include/*.[ch] ./
	doxygen
clean:
	rm -f *.[ch]
