/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef MODEOCCBATADMINSNMPCOMMUNITYTABLE_H
#define MODEOCCBATADMINSNMPCOMMUNITYTABLE_H

/*
 * function declarations 
 */
void            init_modEoCCBATAdminSNMPCommunityTable(void);
void            initialize_table_modEoCCBATAdminSNMPCommunityTable(void);
Netsnmp_Node_Handler modEoCCBATAdminSNMPCommunityTable_handler;
Netsnmp_First_Data_Point
    modEoCCBATAdminSNMPCommunityTable_get_first_data_point;
Netsnmp_Next_Data_Point
    modEoCCBATAdminSNMPCommunityTable_get_next_data_point;

/*
 * column number definitions for table modEoCCBATAdminSNMPCommunityTable 
 */
#define COLUMN_MODEOCCBATADMINSNMPCOMMUNITYINDEX		1
#define COLUMN_MODEOCCBATADMINSNMPCOMMUNITY		2
#define COLUMN_MODEOCCBATADMINSNMPCOMMUNITYPERMISSION		3
#define COLUMN_MODEOCCBATADMINSNMPCOMMUNITYROWSTATUS		4
#endif                          /* MODEOCCBATADMINSNMPCOMMUNITYTABLE_H */
