/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCCNUPortTable.h"

/** Initializes the modEoCCNUPortTable module */
void
init_modEoCCNUPortTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_modEoCCNUPortTable();
}

# Determine the first/last column names

/** Initialize the modEoCCNUPortTable table by defining its contents and how it's structured */
void
initialize_table_modEoCCNUPortTable(void)
{
    static oid      modEoCCNUPortTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 5, 4, 3 };
    size_t          modEoCCNUPortTable_oid_len =
        OID_LENGTH(modEoCCNUPortTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration("modEoCCNUPortTable",
                                            modEoCCNUPortTable_handler,
                                            modEoCCNUPortTable_oid,
                                            modEoCCNUPortTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: modEoCCNUPortCBATCardIndex */
                                     ASN_INTEGER,       /* index: modEoCCNUPortCNUIndex */
                                     ASN_INTEGER,       /* index: modEoCCNUPortIndex */
                                     0);
    table_info->min_column = COLUMN_MODEOCCNUPORTCBATCARDINDEX;
    table_info->max_column = COLUMN_MODEOCCNUPORTSERVICE;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = modEoCCNUPortTable_get_first_data_point;
    iinfo->get_next_data_point = modEoCCNUPortTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct modEoCCNUPortTable_entry {
    /*
     * Index values 
     */
    long            modEoCCNUPortCBATCardIndex;
    long            modEoCCNUPortCNUIndex;
    long            modEoCCNUPortIndex;

    /*
     * Column values 
     */
    long            modEoCCNUPortCBATCardIndex;
    long            modEoCCNUPortCNUIndex;
    long            modEoCCNUPortIndex;
    long            modEoCCNUPortEN;
    long            old_modEoCCNUPortEN;
    long            modEoCCNUPortService;
    long            old_modEoCCNUPortService;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct modEoCCNUPortTable_entry *next;
};

struct modEoCCNUPortTable_entry *modEoCCNUPortTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct modEoCCNUPortTable_entry *
modEoCCNUPortTable_createEntry(long modEoCCNUPortCBATCardIndex,
                               long modEoCCNUPortCNUIndex,
                               long modEoCCNUPortIndex,)
{
    struct modEoCCNUPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct modEoCCNUPortTable_entry);
    if (!entry)
        return NULL;

    entry->modEoCCNUPortCBATCardIndex = modEoCCNUPortCBATCardIndex;
    entry->modEoCCNUPortCNUIndex = modEoCCNUPortCNUIndex;
    entry->modEoCCNUPortIndex = modEoCCNUPortIndex;
    entry->next = modEoCCNUPortTable_head;
    modEoCCNUPortTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
modEoCCNUPortTable_removeEntry(struct modEoCCNUPortTable_entry *entry)
{
    struct modEoCCNUPortTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = modEoCCNUPortTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        modEoCCNUPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
modEoCCNUPortTable_get_first_data_point(void **my_loop_context,
                                        void **my_data_context,
                                        netsnmp_variable_list *
                                        put_index_data,
                                        netsnmp_iterator_info *mydata)
{
    *my_loop_context = modEoCCNUPortTable_head;
    return modEoCCNUPortTable_get_next_data_point(my_loop_context,
                                                  my_data_context,
                                                  put_index_data, mydata);
}

netsnmp_variable_list *
modEoCCNUPortTable_get_next_data_point(void **my_loop_context,
                                       void **my_data_context,
                                       netsnmp_variable_list *
                                       put_index_data,
                                       netsnmp_iterator_info *mydata)
{
    struct modEoCCNUPortTable_entry *entry =
        (struct modEoCCNUPortTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCCNUPortCBATCardIndex);
        idx = idx->next_variable;
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCCNUPortCNUIndex);
        idx = idx->next_variable;
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCCNUPortIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the modEoCCNUPortTable table */
int
modEoCCNUPortTable_handler(netsnmp_mib_handler *handler,
                           netsnmp_handler_registration *reginfo,
                           netsnmp_agent_request_info *reqinfo,
                           netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct modEoCCNUPortTable_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUPortTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUPORTCBATCARDINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUPortCBATCardIndex);
                break;
            case COLUMN_MODEOCCNUPORTCNUINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUPortCNUIndex);
                break;
            case COLUMN_MODEOCCNUPORTINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUPortIndex);
                break;
            case COLUMN_MODEOCCNUPORTEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->modEoCCNUPortEN);
                break;
            case COLUMN_MODEOCCNUPORTSERVICE:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUPortService);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUPortTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUPORTEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUPORTSERVICE:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUPortTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUPORTEN:
                table_entry->old_modEoCCNUPortEN =
                    table_entry->modEoCCNUPortEN;
                table_entry->modEoCCNUPortEN =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCCNUPORTSERVICE:
                table_entry->old_modEoCCNUPortService =
                    table_entry->modEoCCNUPortService;
                table_entry->modEoCCNUPortService =
                    *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUPortTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUPORTEN:
                table_entry->modEoCCNUPortEN =
                    table_entry->old_modEoCCNUPortEN;
                table_entry->old_modEoCCNUPortEN = 0;
                break;
            case COLUMN_MODEOCCNUPORTSERVICE:
                table_entry->modEoCCNUPortService =
                    table_entry->old_modEoCCNUPortService;
                table_entry->old_modEoCCNUPortService = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
