/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCIGMPSnoopingTable.h"

/** Initializes the modEoCIGMPSnoopingTable module */
void
init_modEoCIGMPSnoopingTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_modEoCIGMPSnoopingTable();
}

# Determine the first/last column names

/** Initialize the modEoCIGMPSnoopingTable table by defining its contents and how it's structured */
void
initialize_table_modEoCIGMPSnoopingTable(void)
{
    static oid      modEoCIGMPSnoopingTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 7, 1 };
    size_t          modEoCIGMPSnoopingTable_oid_len =
        OID_LENGTH(modEoCIGMPSnoopingTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration("modEoCIGMPSnoopingTable",
                                            modEoCIGMPSnoopingTable_handler,
                                            modEoCIGMPSnoopingTable_oid,
                                            modEoCIGMPSnoopingTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: modEoCIGMPSnoopingCBATCardIndex */
                                     ASN_INTEGER,       /* index: modEoCIGMPSnoopingCNUIndex */
                                     0);
    table_info->min_column = COLUMN_MODEOCIGMPSNOOPINGCBATCARDINDEX;
    table_info->max_column = COLUMN_MODEOCIGMPSNOOPINGEN;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point =
        modEoCIGMPSnoopingTable_get_first_data_point;
    iinfo->get_next_data_point =
        modEoCIGMPSnoopingTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct modEoCIGMPSnoopingTable_entry {
    /*
     * Index values 
     */
    long            modEoCIGMPSnoopingCBATCardIndex;
    long            modEoCIGMPSnoopingCNUIndex;

    /*
     * Column values 
     */
    long            modEoCIGMPSnoopingCBATCardIndex;
    long            modEoCIGMPSnoopingCNUIndex;
    char            modEoCIGMPSnoopingDevMACAddress[NNN];
    size_t          modEoCIGMPSnoopingDevMACAddress_len;
    char            old_modEoCIGMPSnoopingDevMACAddress[NNN];
    size_t          old_modEoCIGMPSnoopingDevMACAddress_len;
    long            modEoCIGMPSnoopingEN;
    long            old_modEoCIGMPSnoopingEN;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct modEoCIGMPSnoopingTable_entry *next;
};

struct modEoCIGMPSnoopingTable_entry *modEoCIGMPSnoopingTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct modEoCIGMPSnoopingTable_entry *
modEoCIGMPSnoopingTable_createEntry(long modEoCIGMPSnoopingCBATCardIndex,
                                    long modEoCIGMPSnoopingCNUIndex,)
{
    struct modEoCIGMPSnoopingTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct modEoCIGMPSnoopingTable_entry);
    if (!entry)
        return NULL;

    entry->modEoCIGMPSnoopingCBATCardIndex =
        modEoCIGMPSnoopingCBATCardIndex;
    entry->modEoCIGMPSnoopingCNUIndex = modEoCIGMPSnoopingCNUIndex;
    entry->next = modEoCIGMPSnoopingTable_head;
    modEoCIGMPSnoopingTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
modEoCIGMPSnoopingTable_removeEntry(struct modEoCIGMPSnoopingTable_entry
                                    *entry)
{
    struct modEoCIGMPSnoopingTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = modEoCIGMPSnoopingTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        modEoCIGMPSnoopingTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
modEoCIGMPSnoopingTable_get_first_data_point(void **my_loop_context,
                                             void **my_data_context,
                                             netsnmp_variable_list *
                                             put_index_data,
                                             netsnmp_iterator_info *mydata)
{
    *my_loop_context = modEoCIGMPSnoopingTable_head;
    return modEoCIGMPSnoopingTable_get_next_data_point(my_loop_context,
                                                       my_data_context,
                                                       put_index_data,
                                                       mydata);
}

netsnmp_variable_list *
modEoCIGMPSnoopingTable_get_next_data_point(void **my_loop_context,
                                            void **my_data_context,
                                            netsnmp_variable_list *
                                            put_index_data,
                                            netsnmp_iterator_info *mydata)
{
    struct modEoCIGMPSnoopingTable_entry *entry =
        (struct modEoCIGMPSnoopingTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCIGMPSnoopingCBATCardIndex);
        idx = idx->next_variable;
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCIGMPSnoopingCNUIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the modEoCIGMPSnoopingTable table */
int
modEoCIGMPSnoopingTable_handler(netsnmp_mib_handler *handler,
                                netsnmp_handler_registration *reginfo,
                                netsnmp_agent_request_info *reqinfo,
                                netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct modEoCIGMPSnoopingTable_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCIGMPSnoopingTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCIGMPSNOOPINGCBATCARDINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCIGMPSnoopingCBATCardIndex);
                break;
            case COLUMN_MODEOCIGMPSNOOPINGCNUINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCIGMPSnoopingCNUIndex);
                break;
            case COLUMN_MODEOCIGMPSNOOPINGDEVMACADDRESS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         modEoCIGMPSnoopingDevMACAddress,
                                         table_entry->
                                         modEoCIGMPSnoopingDevMACAddress_len);
                break;
            case COLUMN_MODEOCIGMPSNOOPINGEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCIGMPSnoopingEN);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCIGMPSnoopingTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCIGMPSNOOPINGDEVMACADDRESS:
                /*
                 * or possiblc 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              modEoCIGMPSnoopingDevMACAddress));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCIGMPSNOOPINGEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCIGMPSnoopingTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCIGMPSNOOPINGDEVMACADDRESS:
                memcpy(table_entry->old_modEoCIGMPSnoopingDevMACAddress,
                       table_entry->modEoCIGMPSnoopingDevMACAddress,
                       sizeof(table_entry->
                              modEoCIGMPSnoopingDevMACAddress));
                table_entry->old_modEoCIGMPSnoopingDevMACAddress_len =
                    table_entry->modEoCIGMPSnoopingDevMACAddress_len;
                memset(table_entry->modEoCIGMPSnoopingDevMACAddress, 0,
                       sizeof(table_entry->
                              modEoCIGMPSnoopingDevMACAddress));
                memcpy(table_entry->modEoCIGMPSnoopingDevMACAddress,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->modEoCIGMPSnoopingDevMACAddress_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_MODEOCIGMPSNOOPINGEN:
                table_entry->old_modEoCIGMPSnoopingEN =
                    table_entry->modEoCIGMPSnoopingEN;
                table_entry->modEoCIGMPSnoopingEN =
                    *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCIGMPSnoopingTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCIGMPSNOOPINGDEVMACADDRESS:
                memcpy(table_entry->modEoCIGMPSnoopingDevMACAddress,
                       table_entry->old_modEoCIGMPSnoopingDevMACAddress,
                       sizeof(table_entry->
                              modEoCIGMPSnoopingDevMACAddress));
                memset(table_entry->old_modEoCIGMPSnoopingDevMACAddress, 0,
                       sizeof(table_entry->
                              modEoCIGMPSnoopingDevMACAddress));
                table_entry->modEoCIGMPSnoopingDevMACAddress_len =
                    table_entry->old_modEoCIGMPSnoopingDevMACAddress_len;
                break;
            case COLUMN_MODEOCIGMPSNOOPINGEN:
                table_entry->modEoCIGMPSnoopingEN =
                    table_entry->old_modEoCIGMPSnoopingEN;
                table_entry->old_modEoCIGMPSnoopingEN = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
