/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef MODEOCCBATCARDTABLE_H
#define MODEOCCBATCARDTABLE_H

/*
 * function declarations 
 */
void            init_modEoCCBATCardTable(void);
void            initialize_table_modEoCCBATCardTable(void);
Netsnmp_Node_Handler modEoCCBATCardTable_handler;
Netsnmp_First_Data_Point modEoCCBATCardTable_get_first_data_point;
Netsnmp_Next_Data_Point modEoCCBATCardTable_get_next_data_point;

/*
 * column number definitions for table modEoCCBATCardTable 
 */
#define COLUMN_MODEOCCBATCARDINDEX		1
#define COLUMN_MODEOCCBATCARDMACADDRESS		2
#define COLUMN_MODEOCCBATCARDONLINESTATUS		3
#define COLUMN_MODEOCCBATCARDMODELNUMBER		4
#define COLUMN_MODEOCCBATCARDSOFTWAREVERSION		5
#define COLUMN_MODEOCCBATCARDRESET		6
#define COLUMN_MODEOCCBATCARDUPLINKBROADCASTFRAMESENDINTERVALBEFOREACK		7
#define COLUMN_MODEOCCBATCARDUPLINKBROADCASTFRAMESENDINTERVALAFTERACK		8
#define COLUMN_MODEOCCBATCARDUPLINKDEVICEMACADDRESS		9
#define COLUMN_MODEOCCBATCARDUPLINKDEVICEPORTNUMBER		10
#define COLUMN_MODEOCCBATCARDCONFIGURATIONSAVING		11
#define COLUMN_MODEOCCBATCARDCONFIGURATIONRESULT		12
#endif                          /* MODEOCCBATCARDTABLE_H */
