/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef MODEOCCNU_H
#define MODEOCCNU_H

/*
 * function declarations 
 */
void            init_modEoCCNU(void);
Netsnmp_Node_Handler handle_modEoCCNUAllReset;
Netsnmp_Node_Handler handle_modEoCCNUCurrentAmount;
Netsnmp_Node_Handler handle_modEoCCNUAmountLimitation;

#endif                          /* MODEOCCNU_H */
