/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef MODEOCCBATOTHERADMINGROUP_H
#define MODEOCCBATOTHERADMINGROUP_H

/*
 * function declarations 
 */
void            init_modEoCCBATOtherAdminGroup(void);
Netsnmp_Node_Handler handle_modEoCCBATAdminLinkTopoChange;
Netsnmp_Node_Handler handle_modEoCCBATAdminAppropriativeOID;

#endif                          /* MODEOCCBATOTHERADMINGROUP_H */
