/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef MODEOCTRAPGROUP_H
#define MODEOCTRAPGROUP_H

/*
 * function declarations 
 */
void            init_modEoCTrapGroup(void);
Netsnmp_Node_Handler handle_modEoCTrapMaxTimes;
Netsnmp_Node_Handler handle_modEoCTrapMinInterval;
Netsnmp_Node_Handler handle_modEoCTrapMaxInterval;
Netsnmp_Node_Handler handle_modEoCTrapVersion;

#endif                          /* MODEOCTRAPGROUP_H */
