/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef MODEOCCBATRFTABLE_H
#define MODEOCCBATRFTABLE_H

/*
 * function declarations 
 */
void            init_modEoCCBATRFTable(void);
void            initialize_table_modEoCCBATRFTable(void);
Netsnmp_Node_Handler modEoCCBATRFTable_handler;
Netsnmp_First_Data_Point modEoCCBATRFTable_get_first_data_point;
Netsnmp_Next_Data_Point modEoCCBATRFTable_get_next_data_point;

/*
 * column number definitions for table modEoCCBATRFTable 
 */
#define COLUMN_MODEOCCBATRFINDEX		1
#define COLUMN_MODEOCCBATRFLINKMAXIMUM		2
#define COLUMN_MODEOCCBATRFOUTPUTLEVEL		3
#define COLUMN_MODEOCCBATRFDOWNSTREAMSTARTFREQ		4
#define COLUMN_MODEOCCBATRFDOWNSTREAMSTOPFREQ		5
#define COLUMN_MODEOCCBATRFUPSTREAMSTARTFREQ		6
#define COLUMN_MODEOCCBATRFUPSTREAMSTOPFREQ		7
#endif                          /* MODEOCCBATRFTABLE_H */
