/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCCBATOtherAdminGroup.h"

#include "nscrtv.h"

#ifndef DBGID
#define DBGID  "modeocother"
#endif 


/** Initializes the modEoCCBATOtherAdminGroup module */
void
init_modEoCCBATOtherAdminGroup(void)
{
    static oid      modEoCCBATAdminLinkTopoChange_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 1, 5, 1 };
    static oid      modEoCCBATAdminAppropriativeOID_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 1, 5, 2 };

    DEBUGMSGTL(("modEoCCBATOtherAdminGroup", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("modEoCCBATAdminLinkTopoChange",
                             handle_modEoCCBATAdminLinkTopoChange,
                             modEoCCBATAdminLinkTopoChange_oid,
                             OID_LENGTH(modEoCCBATAdminLinkTopoChange_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("modEoCCBATAdminAppropriativeOID",
                             handle_modEoCCBATAdminAppropriativeOID,
                             modEoCCBATAdminAppropriativeOID_oid,
                             OID_LENGTH
                             (modEoCCBATAdminAppropriativeOID_oid),
                             HANDLER_CAN_RWRITE));
}

int
handle_modEoCCBATAdminLinkTopoChange(netsnmp_mib_handler *handler,
                                     netsnmp_handler_registration *reginfo,
                                     netsnmp_agent_request_info *reqinfo,
                                     netsnmp_request_info *requests)
{
	static long value = 0;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&value
                                 /* XXX: a pointer to the scalar's data */
                                 ,
                                 sizeof(value)/*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_modEoCCBATAdminLinkTopoChange\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_modEoCCBATAdminAppropriativeOID(netsnmp_mib_handler *handler,
                                       netsnmp_handler_registration
                                       *reginfo,
                                       netsnmp_agent_request_info *reqinfo,
                                       netsnmp_request_info *requests)
{
    int             ret;
	static oid private_oid[MAX_OID_LEN] = {0};
	static int private_oid_len = 0;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OBJECT_ID,
                                 (u_char *)private_oid
                                 /* XXX: a pointer to the scalar's data */
                                 ,
                                 private_oid_len/*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
    case MODE_SET_RESERVE1:
        /*
         * or you could use netsnmp_check_vb_type_and_size instead 
         */
        ret = netsnmp_check_vb_type(requests->requestvb, ASN_OBJECT_ID);
        if (ret != SNMP_ERR_NOERROR) {
            netsnmp_set_request_error(reqinfo, requests, ret);
        }
        break;

    case MODE_SET_RESERVE2:
        /*
         * XXX malloc "undo" storage buffer 
         */
        break;

    case MODE_SET_FREE:
        /*
         * XXX: free resources allocated in RESERVE1 and/or
         * RESERVE2.  Something failed somewhere, and the states
         * below won't be called. 
         */
        break;

    case MODE_SET_ACTION:
        /*
         * XXX: perform the value change here 
         */
		memcpy(private_oid ,requests->requestvb->val.objid, requests->requestvb->val_len);
		private_oid_len = requests->requestvb->val_len;
        break;

    case MODE_SET_COMMIT:
        /*
         * XXX: delete temporary storage 
         */
        break;

    case MODE_SET_UNDO:
        /*
         * XXX: UNDO and return to previous value for the object 
         */
        break;

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_modEoCCBATAdminAppropriativeOID\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
