/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef MODEOCVLANTABLE_H
#define MODEOCVLANTABLE_H

/*
 * function declarations 
 */
void            init_modEoCVLANTable(void);
void            initialize_table_modEoCVLANTable(void);
Netsnmp_Node_Handler modEoCVLANTable_handler;
Netsnmp_First_Data_Point modEoCVLANTable_get_first_data_point;
Netsnmp_Next_Data_Point modEoCVLANTable_get_next_data_point;

/*
 * column number definitions for table modEoCVLANTable 
 */
#define COLUMN_MODEOCVLANINDEX		1
#define COLUMN_MODEOCVLANNAME		2
#define COLUMN_MODEOCVLANFLAG		3
#define COLUMN_MODEOCVLANROWSTATUS		4
#endif                          /* MODEOCVLANTABLE_H */
