/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef CLTCONFIGSERVICE_H
#define CLTCONFIGSERVICE_H

#define CLTCONFIGMANAGEMENTVLAN 1
#define CLTCONFIGHTTPSADMINSTATUS 2
#define CLTCONFIGSSHADMINSTATUS 3
#define CLTCONFIGSSHPORT 4
#define CLTCONFIGTELNETADMINSTATUS 5
#define CLTCONFIGTELNETPORT 6


/*
 * function declarations 
 */
void            init_cltConfigService(void);
Netsnmp_Node_Handler handle_cltConfigManagementVLAN;
Netsnmp_Node_Handler handle_cltConfigHTTPSAdminStatus;
Netsnmp_Node_Handler handle_cltConfigSSHAdminStatus;
Netsnmp_Node_Handler handle_cltConfigSSHPort;
Netsnmp_Node_Handler handle_cltConfigTelnetAdminStatus;
Netsnmp_Node_Handler handle_cltConfigTelnetPort;

Netsnmp_Node_Handler 	cltConfigService_handler;
NetsnmpCacheLoad 		cltConfigService_load;
NetsnmpCacheFree 		cltConfigService_free;
SNMPAlarmCallback 		cltConfigService_commit;


#endif                          /* CLTCONFIGSERVICE_H */
