cmd_rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o := rsdk-linux-gcc -Wp,-MD,rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/.Le890WB_HV.o.d  -nostdinc -isystem /home/shipeng/rtl86907/aaa/trunk/toolchains/rsdk-1.5.6-5281-EB-2.6.30-0.9.30.3-110915/bin/../lib/gcc/mips-linux/4.4.6/include -Iinclude  -I/home/shipeng/rtl86907/aaa/trunk/product/access/kernel/linux-2.6.x/arch/rlx/include -include include/linux/autoconf.h -Iinclude/soc -D__KERNEL__ -D"VMLINUX_LOAD_ADDRESS=0x80041000" -D"LOADADDR=0x80041000" -D"DATAOFFSET=0" -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -fno-delete-null-pointer-checks -D__LUNA_KERNEL__ -Os -fno-inline -ffunction-sections -mno-check-zero-division -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ffreestanding -EB -UMIPSEB -U_MIPSEB -U__MIPSEB -U__MIPSEB__ -UMIPSEL -U_MIPSEL -U__MIPSEL -U__MIPSEL__ -DMIPSEB -D_MIPSEB -D__MIPSEB -D__MIPSEB__ -Iinclude/asm-rlx -Iarch/rlx/bsp_rtl8686/ -Idrivers/net/rtl86900/sdk/include/ -Idrivers/net/rtl86900/sdk/system/include -I/home/shipeng/rtl86907/aaa/trunk/product/access/kernel/linux-2.6.x/arch/rlx/include/asm/mach-generic -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-dwarf2-cfi-asm -Irtk_voip/include/ -Irtk_voip/voip_drivers/ -Irtk_voip/voip_drivers/zarlink/api_lib-2.16.1/includes/ -Irtk_voip/voip_drivers/zarlink/api_lib-2.16.1/arch/rtl89xxb/   -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(Le890WB_HV)"  -D"KBUILD_MODNAME=KBUILD_STR(Le890WB_HV)"  -c -o rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.c

deps_rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o := \
  rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.c \
  rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.h \

rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o: $(deps_rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o)

$(deps_rtk_voip/voip_drivers/zarlink/api_lib-2.16.1/profiles/Le890WB_HV.o):
