#CLI_FILENAME = nvram

LIB_VERMAJOR = 0
LIB_VERMINOR = 1
LIB_FILENAME = libcfg.so

LIB_CFLAGS  = $(CFLAGS) -shared -I$(SOFTWAREDIR)/include -I$(PDT_INC_DIR)
LIB_LDFLAGS =  -Wl,-soname,$(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR)

CLI_CFLAGS  = $(CFLAGS)
CLI_LDFLAGS = $(LDFLAGS)

HEAD = $(wildcard *.h)
SOURCE = $(wildcard *.c)
OBJ = $(patsubst %.c, %.o, $(SOURCE))

all: libcfg

#$(OBJ): $(HEAD) $(SOURCE)
#	$(CC) $(CLI_CFLAGS) -c -o $@ $<

#libcfg: $(OBJ)
libcfg:
	$(CC) $(LIB_CFLAGS) -c -o vos_config.o  vos_config.c -I ../include
	$(CC) $(LIB_CFLAGS) -c -o vos_hash.o  vos_hash.c -I ../include
	echo "-------------------------"
	echo $(LIB_LDFLAGS)
	echo "+++++++++++++++++++++++++"
	$(CC) $(LIB_CFLAGS) $(LIB_LDFLAGS) -o $(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR) $(OBJ)
	$(CC) $(LIB_CFLAGS) $(LIB_LDFLAGS) -o $(LIB_FILENAME) $(OBJ)
clean:
	rm -f $(CLI_FILENAME) $(LIB_FILENAME)* *.o

install: all
	install -D $(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR) $(ROOTFSDIR)/usr/lib/$(LIB_FILENAME).$(LIB_VERMAJOR).$(LIB_VERMINOR)
