#MODULE_DIR := /home/hxu/work/linux-module/opl_linux_module_my
PWD := $(shell /bin/pwd)

module-objs = opl_reg_mmap.o
obj-m= opl_reg_mmap.o
MODULE_NAME = opl_reg_mmap.ko

#include $(MODULE_DIR)/build/Makefile.conf


