#MODULE_DIR := /home/hxu/work/linux-module/opl_linux_module_my
PWD := $(shell /bin/pwd)

module-objs = opl_cpuif.o
obj-m= opl_cpuif.o
MODULE_NAME = opl_cpuif.ko

#include $(MODULE_DIR)/build/Makefile.conf


