/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef MODEOCCNUWHITELIST_H
#define MODEOCCNUWHITELIST_H

/*
 * function declarations 
 */
void            init_modEoCCNUWhiteList(void);
Netsnmp_Node_Handler handle_modEoCCNUWhiteListAmountLimitation;
Netsnmp_Node_Handler handle_modEoCCNUWhiteListRegisteredAmount;
Netsnmp_Node_Handler handle_modEoCCNUWhiteListAllRFOutputLevel;
Netsnmp_Node_Handler handle_modEoCCNUWhiteListAllExtMACLimitation;
Netsnmp_Node_Handler handle_modEoCCNUWhiteListPhyRateGate;

#endif                          /* MODEOCCNUWHITELIST_H */
