/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef MODEOCCBATDEVSTATUSGROUP_H
#define MODEOCCBATDEVSTATUSGROUP_H

/*
 * function declarations 
 */
void            init_modEoCCBATDevStatusGroup(void);
Netsnmp_Node_Handler handle_modEoCCBATAdminAlarmDetectionControl;
Netsnmp_Node_Handler handle_modEoCCBATAdminStatus;
Netsnmp_Node_Handler handle_modEoCCBATAdminInternalTemperature;
Netsnmp_Node_Handler handle_modEoCCBATAdminTamperStatus;
Netsnmp_Node_Handler handle_modEoCCBATAdminDateAndTime;
Netsnmp_Node_Handler handle_modEoCCBATAdminReset;
Netsnmp_Node_Handler handle_modEoCCBATAdminResetCause;
Netsnmp_Node_Handler handle_modEoCCBATAdminConfigurationSaving;
Netsnmp_Node_Handler handle_modEoCCBATAdminConfigurationResult;

#endif                          /* MODEOCCBATDEVSTATUSGROUP_H */
