/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCCNUWhiteListTable.h"

/** Initializes the modEoCCNUWhiteListTable module */
void
init_modEoCCNUWhiteListTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_modEoCCNUWhiteListTable();
}

# Determine the first/last column names

/** Initialize the modEoCCNUWhiteListTable table by defining its contents and how it's structured */
void
initialize_table_modEoCCNUWhiteListTable(void)
{
    static oid      modEoCCNUWhiteListTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 5, 1, 6 };
    size_t          modEoCCNUWhiteListTable_oid_len =
        OID_LENGTH(modEoCCNUWhiteListTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration("modEoCCNUWhiteListTable",
                                            modEoCCNUWhiteListTable_handler,
                                            modEoCCNUWhiteListTable_oid,
                                            modEoCCNUWhiteListTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: modEoCCNUWhiteListIndex */
                                     0);
    table_info->min_column = COLUMN_MODEOCCNUWHITELISTINDEX;
    table_info->max_column = COLUMN_MODEOCCNUWHITELISTROWSTATUS;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point =
        modEoCCNUWhiteListTable_get_first_data_point;
    iinfo->get_next_data_point =
        modEoCCNUWhiteListTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct modEoCCNUWhiteListTable_entry {
    /*
     * Index values 
     */
    long            modEoCCNUWhiteListIndex;

    /*
     * Column values 
     */
    long            modEoCCNUWhiteListIndex;
    char            modEoCCNUWhiteListMACAddress[NNN];
    size_t          modEoCCNUWhiteListMACAddress_len;
    char            old_modEoCCNUWhiteListMACAddress[NNN];
    size_t          old_modEoCCNUWhiteListMACAddress_len;
    long            modEoCCNUWhiteListAuthorization;
    long            old_modEoCCNUWhiteListAuthorization;
    long            modEoCCNUWhiteListRFOutputLevel;
    long            old_modEoCCNUWhiteListRFOutputLevel;
    long            modEoCCNUWhiteListAutoUpgradeEN;
    long            old_modEoCCNUWhiteListAutoUpgradeEN;
    long            modEoCCNUWhiteListRegisterOnlineState;
    u_long          modEoCCNUWhiteListStartTime;
    u_long          old_modEoCCNUWhiteListStartTime;
    u_long          modEoCCNUWhiteListEndTime;
    u_long          old_modEoCCNUWhiteListEndTime;
    long            modEoCCNUWhiteListRowStatus;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct modEoCCNUWhiteListTable_entry *next;
};

struct modEoCCNUWhiteListTable_entry *modEoCCNUWhiteListTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct modEoCCNUWhiteListTable_entry *
modEoCCNUWhiteListTable_createEntry(long modEoCCNUWhiteListIndex,)
{
    struct modEoCCNUWhiteListTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct modEoCCNUWhiteListTable_entry);
    if (!entry)
        return NULL;

    entry->modEoCCNUWhiteListIndex = modEoCCNUWhiteListIndex;
    entry->next = modEoCCNUWhiteListTable_head;
    modEoCCNUWhiteListTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
modEoCCNUWhiteListTable_removeEntry(struct modEoCCNUWhiteListTable_entry
                                    *entry)
{
    struct modEoCCNUWhiteListTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = modEoCCNUWhiteListTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        modEoCCNUWhiteListTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
modEoCCNUWhiteListTable_get_first_data_point(void **my_loop_context,
                                             void **my_data_context,
                                             netsnmp_variable_list *
                                             put_index_data,
                                             netsnmp_iterator_info *mydata)
{
    *my_loop_context = modEoCCNUWhiteListTable_head;
    return modEoCCNUWhiteListTable_get_next_data_point(my_loop_context,
                                                       my_data_context,
                                                       put_index_data,
                                                       mydata);
}

netsnmp_variable_list *
modEoCCNUWhiteListTable_get_next_data_point(void **my_loop_context,
                                            void **my_data_context,
                                            netsnmp_variable_list *
                                            put_index_data,
                                            netsnmp_iterator_info *mydata)
{
    struct modEoCCNUWhiteListTable_entry *entry =
        (struct modEoCCNUWhiteListTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCCNUWhiteListIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the modEoCCNUWhiteListTable table */
int
modEoCCNUWhiteListTable_handler(netsnmp_mib_handler *handler,
                                netsnmp_handler_registration *reginfo,
                                netsnmp_agent_request_info *reqinfo,
                                netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct modEoCCNUWhiteListTable_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUWhiteListTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUWHITELISTINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListIndex);
                break;
            case COLUMN_MODEOCCNUWHITELISTMACADDRESS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         modEoCCNUWhiteListMACAddress,
                                         table_entry->
                                         modEoCCNUWhiteListMACAddress_len);
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTHORIZATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListAuthorization);
                break;
            case COLUMN_MODEOCCNUWHITELISTRFOUTPUTLEVEL:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListRFOutputLevel);
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTOUPGRADEEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListAutoUpgradeEN);
                break;
            case COLUMN_MODEOCCNUWHITELISTREGISTERONLINESTATE:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListRegisterOnlineState);
                break;
            case COLUMN_MODEOCCNUWHITELISTSTARTTIME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb,
                                           ASN_TIMETICKS,
                                           table_entry->
                                           modEoCCNUWhiteListStartTime);
                break;
            case COLUMN_MODEOCCNUWHITELISTENDTIME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb,
                                           ASN_TIMETICKS,
                                           table_entry->
                                           modEoCCNUWhiteListEndTime);
                break;
            case COLUMN_MODEOCCNUWHITELISTROWSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCCNUWhiteListRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUWhiteListTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUWHITELISTMACADDRESS:
                /*
                 * or possiblc 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              modEoCCNUWhiteListMACAddress));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTHORIZATION:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTRFOUTPUTLEVEL:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTOUPGRADEEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTSTARTTIME:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTENDTIME:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCCNUWHITELISTROWSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                                                 (table_entry ? RS_ACTIVE :
                                                  RS_NONEXISTENT));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUWhiteListTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUWHITELISTMACADDRESS:
                memcpy(table_entry->old_modEoCCNUWhiteListMACAddress,
                       table_entry->modEoCCNUWhiteListMACAddress,
                       sizeof(table_entry->modEoCCNUWhiteListMACAddress));
                table_entry->old_modEoCCNUWhiteListMACAddress_len =
                    table_entry->modEoCCNUWhiteListMACAddress_len;
                memset(table_entry->modEoCCNUWhiteListMACAddress, 0,
                       sizeof(table_entry->modEoCCNUWhiteListMACAddress));
                memcpy(table_entry->modEoCCNUWhiteListMACAddress,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->modEoCCNUWhiteListMACAddress_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTHORIZATION:
                table_entry->old_modEoCCNUWhiteListAuthorization =
                    table_entry->modEoCCNUWhiteListAuthorization;
                table_entry->modEoCCNUWhiteListAuthorization =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCCNUWHITELISTRFOUTPUTLEVEL:
                table_entry->old_modEoCCNUWhiteListRFOutputLevel =
                    table_entry->modEoCCNUWhiteListRFOutputLevel;
                table_entry->modEoCCNUWhiteListRFOutputLevel =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTOUPGRADEEN:
                table_entry->old_modEoCCNUWhiteListAutoUpgradeEN =
                    table_entry->modEoCCNUWhiteListAutoUpgradeEN;
                table_entry->modEoCCNUWhiteListAutoUpgradeEN =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCCNUWHITELISTSTARTTIME:
                table_entry->old_modEoCCNUWhiteListStartTime =
                    table_entry->modEoCCNUWhiteListStartTime;
                table_entry->modEoCCNUWhiteListStartTime =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCCNUWHITELISTENDTIME:
                table_entry->old_modEoCCNUWhiteListEndTime =
                    table_entry->modEoCCNUWhiteListEndTime;
                table_entry->modEoCCNUWhiteListEndTime =
                    *request->requestvb->val.integer;
                break;
            }
        }
        /*
         * Check the internal consistency of an active row 
         */
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUWhiteListTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUWHITELISTROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if ( /* XXX */ ) {
                        netsnmp_set_request_error(reqinfo, request,
                                                  SNMP_ERR_INCONSISTENTVALUE);
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCCNUWhiteListTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCCNUWHITELISTMACADDRESS:
                memcpy(table_entry->modEoCCNUWhiteListMACAddress,
                       table_entry->old_modEoCCNUWhiteListMACAddress,
                       sizeof(table_entry->modEoCCNUWhiteListMACAddress));
                memset(table_entry->old_modEoCCNUWhiteListMACAddress, 0,
                       sizeof(table_entry->modEoCCNUWhiteListMACAddress));
                table_entry->modEoCCNUWhiteListMACAddress_len =
                    table_entry->old_modEoCCNUWhiteListMACAddress_len;
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTHORIZATION:
                table_entry->modEoCCNUWhiteListAuthorization =
                    table_entry->old_modEoCCNUWhiteListAuthorization;
                table_entry->old_modEoCCNUWhiteListAuthorization = 0;
                break;
            case COLUMN_MODEOCCNUWHITELISTRFOUTPUTLEVEL:
                table_entry->modEoCCNUWhiteListRFOutputLevel =
                    table_entry->old_modEoCCNUWhiteListRFOutputLevel;
                table_entry->old_modEoCCNUWhiteListRFOutputLevel = 0;
                break;
            case COLUMN_MODEOCCNUWHITELISTAUTOUPGRADEEN:
                table_entry->modEoCCNUWhiteListAutoUpgradeEN =
                    table_entry->old_modEoCCNUWhiteListAutoUpgradeEN;
                table_entry->old_modEoCCNUWhiteListAutoUpgradeEN = 0;
                break;
            case COLUMN_MODEOCCNUWHITELISTSTARTTIME:
                table_entry->modEoCCNUWhiteListStartTime =
                    table_entry->old_modEoCCNUWhiteListStartTime;
                table_entry->old_modEoCCNUWhiteListStartTime = 0;
                break;
            case COLUMN_MODEOCCNUWHITELISTENDTIME:
                table_entry->modEoCCNUWhiteListEndTime =
                    table_entry->old_modEoCCNUWhiteListEndTime;
                table_entry->old_modEoCCNUWhiteListEndTime = 0;
                break;
            case COLUMN_MODEOCCNUWHITELISTROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        modEoCCNUWhiteListTable_removeEntry(table_data,
                                                            table_row);
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
