/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCBroadcastStormProtectionTable.h"

/** Initializes the modEoCBroadcastStormProtectionTable module */
void
init_modEoCBroadcastStormProtectionTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_modEoCBroadcastStormProtectionTable();
}

# Determine the first/last column names

/** Initialize the modEoCBroadcastStormProtectionTable table by defining its contents and how it's structured */
void
initialize_table_modEoCBroadcastStormProtectionTable(void)
{
    static oid      modEoCBroadcastStormProtectionTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 10, 1 };
    size_t          modEoCBroadcastStormProtectionTable_oid_len =
        OID_LENGTH(modEoCBroadcastStormProtectionTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration
        ("modEoCBroadcastStormProtectionTable",
         modEoCBroadcastStormProtectionTable_handler,
         modEoCBroadcastStormProtectionTable_oid,
         modEoCBroadcastStormProtectionTable_oid_len, HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: modEoCBroadcastStormProtectionCBATCardIndex */
                                     0);
    table_info->min_column =
        COLUMN_MODEOCBROADCASTSTORMPROTECTIONCBATCARDINDEX;
    table_info->max_column = COLUMN_MODEOCUNKNOWNUNICASTSTORMTHRESHOLD;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point =
        modEoCBroadcastStormProtectionTable_get_first_data_point;
    iinfo->get_next_data_point =
        modEoCBroadcastStormProtectionTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct modEoCBroadcastStormProtectionTable_entry {
    /*
     * Index values 
     */
    long            modEoCBroadcastStormProtectionCBATCardIndex;

    /*
     * Column values 
     */
    long            modEoCBroadcastStormProtectionCBATCardIndex;
    long            modEoCBroadcastStormProtectionCNUIndex;
    long            modEoCBroadcastStormProtectionPortIndex;
    long            modEoCBroadcastStormProtectionEN;
    long            old_modEoCBroadcastStormProtectionEN;
    long            modEoCBroadcastStormThreshold;
    long            old_modEoCBroadcastStormThreshold;
    long            modEoCMulticastStormProtectionEN;
    long            old_modEoCMulticastStormProtectionEN;
    long            modEoCMulticastStormThreshold;
    long            old_modEoCMulticastStormThreshold;
    long            modEoCUnknownUnicastStormProtectionEN;
    long            old_modEoCUnknownUnicastStormProtectionEN;
    long            modEoCUnknownUnicastStormThreshold;
    long            old_modEoCUnknownUnicastStormThreshold;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct modEoCBroadcastStormProtectionTable_entry *next;
};

struct modEoCBroadcastStormProtectionTable_entry
    *modEoCBroadcastStormProtectionTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct modEoCBroadcastStormProtectionTable_entry *
modEoCBroadcastStormProtectionTable_createEntry(long
                                                modEoCBroadcastStormProtectionCBATCardIndex,)
{
    struct modEoCBroadcastStormProtectionTable_entry *entry;

    entry =
        SNMP_MALLOC_TYPEDEF(struct
                            modEoCBroadcastStormProtectionTable_entry);
    if (!entry)
        return NULL;

    entry->modEoCBroadcastStormProtectionCBATCardIndex =
        modEoCBroadcastStormProtectionCBATCardIndex;
    entry->next = modEoCBroadcastStormProtectionTable_head;
    modEoCBroadcastStormProtectionTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
modEoCBroadcastStormProtectionTable_removeEntry(struct
                                                modEoCBroadcastStormProtectionTable_entry
                                                *entry)
{
    struct modEoCBroadcastStormProtectionTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = modEoCBroadcastStormProtectionTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        modEoCBroadcastStormProtectionTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
modEoCBroadcastStormProtectionTable_get_first_data_point(void
                                                         **my_loop_context,
                                                         void
                                                         **my_data_context,
                                                         netsnmp_variable_list
                                                         * put_index_data,
                                                         netsnmp_iterator_info
                                                         *mydata)
{
    *my_loop_context = modEoCBroadcastStormProtectionTable_head;
    return
        modEoCBroadcastStormProtectionTable_get_next_data_point
        (my_loop_context, my_data_context, put_index_data, mydata);
}

netsnmp_variable_list *
modEoCBroadcastStormProtectionTable_get_next_data_point(void
                                                        **my_loop_context,
                                                        void
                                                        **my_data_context,
                                                        netsnmp_variable_list
                                                        * put_index_data,
                                                        netsnmp_iterator_info
                                                        *mydata)
{
    struct modEoCBroadcastStormProtectionTable_entry *entry =
        (struct modEoCBroadcastStormProtectionTable_entry *)
        *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->
                                   modEoCBroadcastStormProtectionCBATCardIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the modEoCBroadcastStormProtectionTable table */
int
modEoCBroadcastStormProtectionTable_handler(netsnmp_mib_handler *handler,
                                            netsnmp_handler_registration
                                            *reginfo,
                                            netsnmp_agent_request_info
                                            *reqinfo,
                                            netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct modEoCBroadcastStormProtectionTable_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry =
                (struct modEoCBroadcastStormProtectionTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONCBATCARDINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCBroadcastStormProtectionCBATCardIndex);
                break;
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONCNUINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCBroadcastStormProtectionCNUIndex);
                break;
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONPORTINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCBroadcastStormProtectionPortIndex);
                break;
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCBroadcastStormProtectionEN);
                break;
            case COLUMN_MODEOCBROADCASTSTORMTHRESHOLD:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCBroadcastStormThreshold);
                break;
            case COLUMN_MODEOCMULTICASTSTORMPROTECTIONEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCMulticastStormProtectionEN);
                break;
            case COLUMN_MODEOCMULTICASTSTORMTHRESHOLD:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCMulticastStormThreshold);
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMPROTECTIONEN:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCUnknownUnicastStormProtectionEN);
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMTHRESHOLD:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCUnknownUnicastStormThreshold);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry =
                (struct modEoCBroadcastStormProtectionTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCBROADCASTSTORMTHRESHOLD:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCMULTICASTSTORMPROTECTIONEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCMULTICASTSTORMTHRESHOLD:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMPROTECTIONEN:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMTHRESHOLD:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry =
                (struct modEoCBroadcastStormProtectionTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONEN:
                table_entry->old_modEoCBroadcastStormProtectionEN =
                    table_entry->modEoCBroadcastStormProtectionEN;
                table_entry->modEoCBroadcastStormProtectionEN =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCBROADCASTSTORMTHRESHOLD:
                table_entry->old_modEoCBroadcastStormThreshold =
                    table_entry->modEoCBroadcastStormThreshold;
                table_entry->modEoCBroadcastStormThreshold =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCMULTICASTSTORMPROTECTIONEN:
                table_entry->old_modEoCMulticastStormProtectionEN =
                    table_entry->modEoCMulticastStormProtectionEN;
                table_entry->modEoCMulticastStormProtectionEN =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCMULTICASTSTORMTHRESHOLD:
                table_entry->old_modEoCMulticastStormThreshold =
                    table_entry->modEoCMulticastStormThreshold;
                table_entry->modEoCMulticastStormThreshold =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMPROTECTIONEN:
                table_entry->old_modEoCUnknownUnicastStormProtectionEN =
                    table_entry->modEoCUnknownUnicastStormProtectionEN;
                table_entry->modEoCUnknownUnicastStormProtectionEN =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMTHRESHOLD:
                table_entry->old_modEoCUnknownUnicastStormThreshold =
                    table_entry->modEoCUnknownUnicastStormThreshold;
                table_entry->modEoCUnknownUnicastStormThreshold =
                    *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry =
                (struct modEoCBroadcastStormProtectionTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCBROADCASTSTORMPROTECTIONEN:
                table_entry->modEoCBroadcastStormProtectionEN =
                    table_entry->old_modEoCBroadcastStormProtectionEN;
                table_entry->old_modEoCBroadcastStormProtectionEN = 0;
                break;
            case COLUMN_MODEOCBROADCASTSTORMTHRESHOLD:
                table_entry->modEoCBroadcastStormThreshold =
                    table_entry->old_modEoCBroadcastStormThreshold;
                table_entry->old_modEoCBroadcastStormThreshold = 0;
                break;
            case COLUMN_MODEOCMULTICASTSTORMPROTECTIONEN:
                table_entry->modEoCMulticastStormProtectionEN =
                    table_entry->old_modEoCMulticastStormProtectionEN;
                table_entry->old_modEoCMulticastStormProtectionEN = 0;
                break;
            case COLUMN_MODEOCMULTICASTSTORMTHRESHOLD:
                table_entry->modEoCMulticastStormThreshold =
                    table_entry->old_modEoCMulticastStormThreshold;
                table_entry->old_modEoCMulticastStormThreshold = 0;
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMPROTECTIONEN:
                table_entry->modEoCUnknownUnicastStormProtectionEN =
                    table_entry->old_modEoCUnknownUnicastStormProtectionEN;
                table_entry->old_modEoCUnknownUnicastStormProtectionEN = 0;
                break;
            case COLUMN_MODEOCUNKNOWNUNICASTSTORMTHRESHOLD:
                table_entry->modEoCUnknownUnicastStormThreshold =
                    table_entry->old_modEoCUnknownUnicastStormThreshold;
                table_entry->old_modEoCUnknownUnicastStormThreshold = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
