/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "modEoCTrapTable.h"

/** Initializes the modEoCTrapTable module */
void
init_modEoCTrapTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_modEoCTrapTable();
}

# Determine the first/last column names

/** Initialize the modEoCTrapTable table by defining its contents and how it's structured */
void
initialize_table_modEoCTrapTable(void)
{
    static oid      modEoCTrapTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 2, 4, 8, 5 };
    size_t          modEoCTrapTable_oid_len =
        OID_LENGTH(modEoCTrapTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration("modEoCTrapTable",
                                            modEoCTrapTable_handler,
                                            modEoCTrapTable_oid,
                                            modEoCTrapTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: modEoCTrapIndex */
                                     0);
    table_info->min_column = COLUMN_MODEOCTRAPINDEX;
    table_info->max_column = COLUMN_MODEOCTRAPROWSTATUS;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = modEoCTrapTable_get_first_data_point;
    iinfo->get_next_data_point = modEoCTrapTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct modEoCTrapTable_entry {
    /*
     * Index values 
     */
    long            modEoCTrapIndex;

    /*
     * Column values 
     */
    long            modEoCTrapIndex;
    u_long          modEoCTrapIP;
    u_long          old_modEoCTrapIP;
    char            modEoCTrapCommunity[NNN];
    size_t          modEoCTrapCommunity_len;
    char            old_modEoCTrapCommunity[NNN];
    size_t          old_modEoCTrapCommunity_len;
    long            modEoCTrapStatus;
    long            old_modEoCTrapStatus;
    long            modEoCTrapRowStatus;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct modEoCTrapTable_entry *next;
};

struct modEoCTrapTable_entry *modEoCTrapTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct modEoCTrapTable_entry *
modEoCTrapTable_createEntry(long modEoCTrapIndex,)
{
    struct modEoCTrapTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct modEoCTrapTable_entry);
    if (!entry)
        return NULL;

    entry->modEoCTrapIndex = modEoCTrapIndex;
    entry->next = modEoCTrapTable_head;
    modEoCTrapTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
modEoCTrapTable_removeEntry(struct modEoCTrapTable_entry *entry)
{
    struct modEoCTrapTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = modEoCTrapTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        modEoCTrapTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
modEoCTrapTable_get_first_data_point(void **my_loop_context,
                                     void **my_data_context,
                                     netsnmp_variable_list *
                                     put_index_data,
                                     netsnmp_iterator_info *mydata)
{
    *my_loop_context = modEoCTrapTable_head;
    return modEoCTrapTable_get_next_data_point(my_loop_context,
                                               my_data_context,
                                               put_index_data, mydata);
}

netsnmp_variable_list *
modEoCTrapTable_get_next_data_point(void **my_loop_context,
                                    void **my_data_context,
                                    netsnmp_variable_list * put_index_data,
                                    netsnmp_iterator_info *mydata)
{
    struct modEoCTrapTable_entry *entry =
        (struct modEoCTrapTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->modEoCTrapIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the modEoCTrapTable table */
int
modEoCTrapTable_handler(netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info *reqinfo,
                        netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct modEoCTrapTable_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCTRAPINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->modEoCTrapIndex);
                break;
            case COLUMN_MODEOCTRAPIP:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb,
                                           ASN_IPADDRESS,
                                           table_entry->modEoCTrapIP);
                break;
            case COLUMN_MODEOCTRAPCOMMUNITY:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         modEoCTrapCommunity,
                                         table_entry->
                                         modEoCTrapCommunity_len);
                break;
            case COLUMN_MODEOCTRAPSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->modEoCTrapStatus);
                break;
            case COLUMN_MODEOCTRAPROWSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           modEoCTrapRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCTRAPIP:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCTRAPCOMMUNITY:
                /*
                 * or possiblc 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              modEoCTrapCommunity));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCTRAPSTATUS:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MODEOCTRAPROWSTATUS:
                ret = netsnmp_check_vb_rowstatus(request->requestvb,
                                                 (table_entry ? RS_ACTIVE :
                                                  RS_NONEXISTENT));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCTRAPIP:
                table_entry->old_modEoCTrapIP = table_entry->modEoCTrapIP;
                table_entry->modEoCTrapIP =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_MODEOCTRAPCOMMUNITY:
                memcpy(table_entry->old_modEoCTrapCommunity,
                       table_entry->modEoCTrapCommunity,
                       sizeof(table_entry->modEoCTrapCommunity));
                table_entry->old_modEoCTrapCommunity_len =
                    table_entry->modEoCTrapCommunity_len;
                memset(table_entry->modEoCTrapCommunity, 0,
                       sizeof(table_entry->modEoCTrapCommunity));
                memcpy(table_entry->modEoCTrapCommunity,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->modEoCTrapCommunity_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_MODEOCTRAPSTATUS:
                table_entry->old_modEoCTrapStatus =
                    table_entry->modEoCTrapStatus;
                table_entry->modEoCTrapStatus =
                    *request->requestvb->val.integer;
                break;
            }
        }
        /*
         * Check the internal consistency of an active row 
         */
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCTRAPROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if ( /* XXX */ ) {
                        netsnmp_set_request_error(reqinfo, request,
                                                  SNMP_ERR_INCONSISTENTVALUE);
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct modEoCTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_MODEOCTRAPIP:
                table_entry->modEoCTrapIP = table_entry->old_modEoCTrapIP;
                table_entry->old_modEoCTrapIP = 0;
                break;
            case COLUMN_MODEOCTRAPCOMMUNITY:
                memcpy(table_entry->modEoCTrapCommunity,
                       table_entry->old_modEoCTrapCommunity,
                       sizeof(table_entry->modEoCTrapCommunity));
                memset(table_entry->old_modEoCTrapCommunity, 0,
                       sizeof(table_entry->modEoCTrapCommunity));
                table_entry->modEoCTrapCommunity_len =
                    table_entry->old_modEoCTrapCommunity_len;
                break;
            case COLUMN_MODEOCTRAPSTATUS:
                table_entry->modEoCTrapStatus =
                    table_entry->old_modEoCTrapStatus;
                table_entry->old_modEoCTrapStatus = 0;
                break;
            case COLUMN_MODEOCTRAPROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_CREATEANDGO:
                case RS_CREATEANDWAIT:
                    if (table_entry && !table_entry->valid) {
                        modEoCTrapTable_removeEntry(table_data, table_row);
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
