/*
=============================================================================
     File Name: ipc_hal.h

     General Description:
===============================================================================
                         Opulan Confidential Proprietary                     
                  ID and version: xxxxxxxxxxxxxx  Version 1.00
                  (c) Copyright Opulan XXXX - XXXX, All Rights Reserved     

Revision History:
Author                Date              Description of Changes
----------------   ------------  ----------------------------------------------
			2008/8/19		Initial Version	
----------------   ------------  ----------------------------------------------
*/
#ifndef __IPC_HAL_H__
#define __IPC_HAL_H__

typedef void (*IPC_HAL_FUNC)(void* ptr,int len);

typedef unsigned int IPC_HAL_RESULT;        /* 0 - ok, otherwise - false */
typedef unsigned int IPC_HAL_API_ID;
typedef unsigned int IPC_HAL_DEVICE_ID;

#define ERROR -1
#define NO_ERROR 0

typedef enum EVENT_ID_s
{
  OP_EVENT_OVERVIEW = 0,
  OP_ONU_STATUS_GET,
  OP_ONU_VERSION_GET,
  OP_ONU_UPTIME_GET,
  OP_ONU_CAPABILITIY_GET,
  OP_ONU_CHIPSET_GET,
  OP_ONU_CHECKSUM_GET,
  OP_EVENT_ONU_CONF = 10,
  OP_ONU_FECMODE_GET,
  OP_ONU_FECMODE_SET,
  OP_ONU_CTC_STATUS_GET,
  OP_ONU_CTC_STATUS_SET,
  OP_ONU_MACADDRESS_GET,
  OP_ONU_MACADDRESS_SET,
  OP_ONU_OUI_GET,
  OP_ONU_OUI_SET,
  OP_ONU_SN_GET,
  OP_ONU_SN_SET,
  OP_ONU_PON_MAC_GET,
  OP_EVENT_BPDU_CONF = 25,
  OP_BPDU_TRANS_GET,
  OP_BPDU_TRANS_SET,
  OP_EVENT_IP_CONF = 30, 
  OP_IPADDR_GET,
  OP_IPMASK_GET,
  OP_IPADDR_SET,
  OP_IPMASK_SET,
  OP_IP_GATEWAY_GET,
  OP_IP_GATEWAY_SET,
  OP_IP_DNS_GET,
  OP_IP_DNS_SET,
  OP_EVENT_MTU_CONF = 40,
  OP_PON_MTU_SET,
  OP_PON_MTU_GET,
  OP_EVENT_FRAM_FILT = 50,
  OP_FRAM_FILTER_GET,
  OP_FRAM_FILTER_SET,
  OP_FRAM_FILTER_DEL,
  OP_EVENT_MAC_FILTANDBIND = 60,
  OP_PORT_MAC_BIND_GET,
  OP_PORT_MAC_BIND_SET,
  OP_PORT_MAC_BIND_DEL,
  OP_PORT_MAC_FILTER_GET,
  OP_PORT_MAC_FILTER_SET,
  OP_PORT_MAC_FILTER_DEL,
  OP_MAC_LIMIT_STATUS_GET,
  OP_MAC_LIMIT_STATUS_SET,
  OP_PORT_MACLIMIT_NUM_GET,
  OP_PORT_MACLIMIT_NUM_SET,
  OP_MAC_BIND_STATUS_GET,
  OP_MAC_BIND_STATUS_SET,
  OP_EVENT_QUE_CONF = 80,
  OP_PQUEUE_INGRESS_LIMIT_GET,
  OP_PQUEUE_QUEUE_BLOCK_SET,
  OP_PQUEUE_INLIMIT_OCCUPANCY_GET,
  OP_EVENT_SWI_CONF = 90,
  OP_PORT_ISOLATE_STATUS_GET,
  OP_PORT_ISOLATE_STATUS_SET,
  OP_EXTEND_MTU_STATUS_GET,
  OP_EXTEND_MTU_STATUS_SET,
  OP_PORT_SPEED_MODE_GET,
  OP_PORT_SPEED_MODE_SET,
  OP_PORT_STORM_RESTRAIN_GET,
  OP_PORT_STORM_RESTRAIN_SET,
  OP_EVENT_PORT_CONF = 100,
  OP_PORT_CONF_GET,
  OP_PORT_CONF_SET,
  OP_EVENT_VLAN_CONF = 110,
  OP_PORT_LINK_STATE_GET,
  OP_PORT_VLAN_MODE_GET,
  OP_PORT_PVID_GET,
  OP_PORT_VLAN_MODE_SET,
  OP_PORT_PVID_SET,
  OP_VLAN_INFO_GET,
  OP_VLAN_MEMBER_SET,
  OP_VLAN_MEMBER_DEL,  
  OP_EVENT_QOS_CONF = 120,
  OP_QOS_SCHEDULING_MODE_GET,
  OP_QOS_SCHEDULING_MODE_SET,
  OP_POLICY_QUEUE_MAPPING_GET,
  OP_POLICY_QUEUE_MAPPING_SET,
  OP_QUEUE_MAPPING_ENABLE_GET,
  OP_QUEUE_MAPPING_ENABLE_SET,
  OP_VLAN_PRI_TRANSLATION_GET,
  OP_VLAN_PRI_TRANSLATION_SET,
  OP_EVENT_MULTICAST_CONF = 130,
  OP_IGMP_SNOOP_ENABLE_GET,
  OP_IGMP_SNOOP_ENABLE_SET,
  OP_IGMP_SNOOP_MAC_AGINGTIME_GET,
  OP_IGMP_SNOOP_MAC_AGINGTIME_SET,
  OP_EVENT_ADDR_TAB = 140,
  OP_MAC_AGING_TIME_GET,
  OP_MAC_AGING_TIME_SET,
  OP_MAC_NUM_GET,
  OP_MAC_GET_MAC_LIST,
  OP_EVENT_MACLEARN_LIMIT = 150,
  OP_MAC_LEARN_LIMIT_GET,
  OP_MAC_LEARN_LIMIT_SET,
  OP_EVENT_DIAGNOSTICS = 160,
  OP_DIAG_STATISTICS_GET,
  OP_DIAG_GSTATS_PORT_ALL_COUNTERS3_GET,
  OP_DIAG_GSTATS_FLUSH_ALL,
  OP_DIAG_GSTATS_FLUSH_PORT,
  OP_REALTIME_STATISTICS_GET,
  OP_REALTIME_ALL_STATISTICS_CLEAR,
  OP_REALTIME_STATISTICS_CLEAR,
  OP_PORT_MIRROR_SRC_STATE_GET,
  OP_PORT_MIRROR_SRC_STATE_SET,
  OP_PORT_MIRROR_DEST_PORT_GET,
  OP_PORT_MIRROR_DEST_PORT_SET,
  OP_EVENT_UPDATE_FIRMWARE = 180,
  OP_ONU_MODE_GET,
  OP_ONU_MODE_SET,
  OP_FLASH_ERASE,
  OP_FLASH_READ,
  OP_FLASH_WRITE,
  OP_EMAPPER_GET,
  OP_EMAPPER_SET,  
  OP_EEPROM_READ,
  OP_FLASH_IMAGE_ACTIVE_GET,
  OP_FLASH_IMAGE_ACTIVE_SET,
  OP_FLASH_IMAGE_BURN,
  OP_ONU_LASER_ON_ENABLE_GET,
  OP_ONU_LASER_ON_ENABLE_SET,
  OP_ONU_LED_CONFIG_SET,
  OP_SIP_DEV_CFG_DATA_GET,
  OP_SIP_DEV_CFG_DATA_SET,
  OP_SIP_INIT_CFG,
  OP_FREE_SIP_VIRTUALINTERFACE,
  OP_VOIP_RESET,   
  OP_SIP_NETWORK_CONFIG_SET,
  OP_MODIFY_PON_ADDRESS,
  OP_NET_DEVICE_CREATE,
  OP_DEV_CFG_DATA_CLEAR,
  OP_RESOLV_CONF_SET,
  OP_EVENT_RESET_ONU = 210,
  OP_RESET_ONU,
  OP_RESET_ONU_TO_DEFAULT,
  OP_ONU_SAVE_CONFIG,
  OP_ONU_EXPORT_CONFIG,
  OP_ONU_BURN_CONFIG,  
  OP_EVENT_ADMIN_ACCOUNT = 220,
  OP_ADMIN_SECURITY_CONFIG_SET,
  OP_EVENT_USER_ACCOUNT = 230,
  OP_USER_SECURITY_CONFIG_SET,
  OP_USERNAME_PASSWORD_SET,
  OP_NIC_NAME_GET,
  OP_MGMT_VER_UPDATE_GET,
  OP_MGMT_VER_UPDATE_SET,
  OP_PHY_LOOPBACK_STATUS_SET =260,
  
  OP_EVENT_VOIP_CONFIG = 300,
  OP_VOIP_INIT,
  OP_VOIP_EXIT,
  OP_VOIP_POSTGROUPBEGIN,
  OP_VOIP_POSTGROUPEND,
  OP_VOIP_SETPORT,
  OP_VOIP_SETCFG,
  OP_VOIP_GETCFG,
  OP_VOIP_GETSTATUS,
  OP_VOIP_ACTIVENWKCFG,
  OP_VOIP_INACTIVENWKCFG,
  OP_VOIP_REPORTNWKSTATUS,
  OP_VOIP_SWITCHSTACK,
  OP_VOIP_GETPROTOCOLTYPE,
  OP_VOIP_FWIUPLOAD,
  OP_VOIP_FWCUPLOAD,
  OP_VOIP_FWSCUPLOAD,
  OP_VOIP_GETFWUPDATESTATE,
  OP_VOIP_GETCFGSTATE,
  OP_VOIP_FWCDOWNLOAD,
  OP_VOIP_RESET_SYSTEM,
  OP_VOIP_ERASE_CONFIG,
  OP_VOIP_ERASE_SCONFIG,
  OP_VOIP_ERASE_VSCONFIG,
  OP_VOIP_GETVOIPSTATE,
  OP_VOIP_CONTROLVOIP,
  OP_VOIP_SETSNTPCFG,
  OP_VOIP_GETSNTPCFG,
  OP_VOIP_CLI_SET,
  OP_VOIP_CLI_SHOW,
  OP_VOIP_GETCFG_,
  OP_VOIP_DSP_SET,
  OP_VOIP_CALCRCMEM,
  OP_VOIP_CALCRCFILE,
  OP_VOIP_SETCOUNTRY,
  OP_VOIP_REPORTPONSTATUS,

/// EricYang add for TW 
  OP_IF_CFG_DATA = 450,
  OP_IF_CFG_DATA_SET,
  OP_IF_CFG_DATA_GET,
///!EricYang
  OP_LOID_SET,
  OP_LOID_GET,
  OP_LOID_PASSWD_SET,
  OP_LOID_PASSWD_GET,
  OP_CTC_STACK_CONFIG_GET,
  OP_ONU_BUILDTIME_GET,
  OP_PORT_STORM_USRATE_SET,
  OP_PORT_STORM_USRATE_GET,
  OP_PORT_STORM_DSRATE_SET,
  OP_PORT_STORM_DSRATE_GET,  
  OP_PRINTF_SET,
  
  //add by lizhe 
  OP_OAM_DEBUG,
  OP_ONU_FILTER_TOTALNUM_Get,
  OP_ONU_CAPABILITIY2_GET,
  OP_ONU_CTC_VER_GET,
  MAX_IPC_COMMAND_FUNC
}EVENT_ID_t;



#define IPCHAL_CHECK_RETURN if (!s_nIpcHalInitialized) return (ERROR)

typedef struct OPL_IPC_API_UNIT_s
{
    IPC_HAL_API_ID          apiId;
    IPC_HAL_FUNC        apiFunc;
} OPL_IPC_API_UNIT_t;

typedef struct OPL_IPC_DATA_s
{
    IPC_HAL_API_ID          apiId;	
	void		*tlvbuff;	
	int			tlvlen;
} OPL_IPC_DATA_t;

typedef struct OPL_IPC_DEV_DRV_s
{
    IPC_HAL_DEVICE_ID       devId;
    OPL_IPC_API_UNIT_t  ipcarrayAPI[MAX_IPC_COMMAND_FUNC];
} OPL_IPC_DEV_DRV_t;

#define IPC_DEVICE_DRV_LOCK vosMutexTake(&s_pstIpcDrvLock)
#define IPC_DEVICE_DRV_UNLOCK vosMutexGive(&s_pstIpcDrvLock)

IPC_HAL_RESULT  IpcHalRegister(void);
IPC_HAL_RESULT  IpcHalDrvApiRegister(OPL_IPC_API_UNIT_t *pstApiUnit);
IPC_HAL_RESULT	IpcHalInit();
IPC_HAL_RESULT  IpcHalAppApiCallSync(OPL_IPC_DATA_t *pstData);

#endif

