
#
# Makefile for some libs needed by zImage.
#

lib-y := $(addprefix ../../../../../lib/zlib_inflate/, \
       inflate_syms.o  inffast.o inflate.o inftrees.o ) \
       $(addprefix ../../../../../lib/, ctype.o string.o) \
       $(addprefix ../../../../../arch/rlx/lib/, memcpy.o) \


