#
# arch/mips/boot/compressed/common/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Tom Rini     January 2001
#
# Pete Popov, 2004
#

lib-y          := misc-common.o no_initrd.o dummy.o
lib-y          += idisx_uart.o

