/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef ALARMLOGTABLE_H
#define ALARMLOGTABLE_H
config_add_mib(EPN104ZG-MIB-V1)
config_require(util_funcs/header_generic)
config_require(EPN104/alarmLogTable)

/*
 * function declarations 
 */
void            init_alarmLogTable(void);
void            initialize_table_alarmLogTable(void);
Netsnmp_Node_Handler alarmLogTable_handler;
Netsnmp_First_Data_Point alarmLogTable_get_first_data_point;
Netsnmp_Next_Data_Point alarmLogTable_get_next_data_point;
NetsnmpCacheLoad         alarmLogTable_load;
NetsnmpCacheFree         alarmLogTable_free;

/*
 * column number definitions for table alarmLogTable 
 */
#define COLUMN_ALARMLOGINDEX		1
#define COLUMN_ALARMLOGINFORMATION		2

#define ALARMLOGINFO_MAX_LEH   255  

#endif                          /* ALARMLOGTABLE_H */
