/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "alarmsIdent.h"

#include "../product_common/snmp_ipc_interface.h"
#include "../product_common/snmp_ipc_interfaceTC.h"

extern int alarmLogIndexNum;
extern int alarmLogLastIndexNum;
extern int alarmLogNumberEntries;

/** Initializes the alarmsIdent module */
void
init_alarmsIdent(void)
{
    const oid       alarmLogNumberOfEntries_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 1, 2, 1 };
    const oid       alarmLogLastIndex_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 1, 2, 2 };
    const oid       alarmText_oid[] = { 1, 3, 6, 1, 4, 1, 17409, 1, 2, 4 };

    DEBUGMSGTL(("alarmsIdent", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("alarmLogNumberOfEntries",
                             handle_alarmLogNumberOfEntries,
                             alarmLogNumberOfEntries_oid,
                             OID_LENGTH(alarmLogNumberOfEntries_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("alarmLogLastIndex", handle_alarmLogLastIndex,
                             alarmLogLastIndex_oid,
                             OID_LENGTH(alarmLogLastIndex_oid),
                             HANDLER_CAN_RONLY));
	#if 1
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("alarmText", handle_alarmText, alarmText_oid,
                             OID_LENGTH(alarmText_oid),
                             HANDLER_CAN_RONLY));
	#endif
}

int
handle_alarmLogNumberOfEntries(netsnmp_mib_handler *handler,
                               netsnmp_handler_registration *reginfo,
                               netsnmp_agent_request_info *reqinfo,
                               netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
	unsigned long alarmLogNumber = 1;
	alarmLogNumber = alarmLogNumberEntries;

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&alarmLogNumber
                                 /* XXX: a pointer to the scalar's data */
                                 ,sizeof(alarmLogNumber)
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_alarmLogNumberOfEntries\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_alarmLogLastIndex(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *reqinfo,
                         netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
	unsigned long alarmLastIndex = 0;
	alarmLastIndex = alarmLogLastIndexNum;

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&alarmLastIndex
                                 /* XXX: a pointer to the scalar's data */
                                 ,sizeof(alarmLastIndex)
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_alarmLogLastIndex\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
#if 1
int
handle_alarmText(netsnmp_mib_handler *handler,
                 netsnmp_handler_registration *reginfo,
                 netsnmp_agent_request_info *reqinfo,
                 netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
char val[16] = "current: ";
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                 (u_char *)val
                                 /* XXX: a pointer to the scalar's data */
                                 ,strlen(val)
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_alarmText\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
#endif
