/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "commonAgentTrapTable.h"

#include "../product_common/snmp_ipc_interface.h"
#include "../product_common/snmp_ipc_interfaceTC.h"
/** Initializes the commonAgentTrapTable module */				
typedef struct {
    long            commonAgentTrapIndex;
	in_addr_t       commonAgentTrapIP;
	char            commonAgentTrapCommunity[MAX_COMMUNITY_SIZE];
    size_t          commonAgentTrapCommunity_len;
    long            commonAgentTrapStatus;

}snmp_commonAgentTrap_t;
snmp_commonAgentTrap_t g_commonAgentTrap;

void
init_commonAgentTrapTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_commonAgentTrapTable();
}

//# Determine the first/last column names

/** Initialize the commonAgentTrapTable table by defining its contents and how it's structured */
void
initialize_table_commonAgentTrapTable(void)
{
    const oid       commonAgentTrapTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 17409, 1, 3, 3, 1, 7 };
    const size_t    commonAgentTrapTable_oid_len =
        OID_LENGTH(commonAgentTrapTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("commonAgentTrapTable:init",
                "initializing table commonAgentTrapTable\n"));

	g_commonAgentTrap.commonAgentTrapIndex = 1;
	g_commonAgentTrap.commonAgentTrapIP = inet_addr("192.168.0.123"); 
	strncpy(g_commonAgentTrap.commonAgentTrapCommunity, "public", sizeof(g_commonAgentTrap.commonAgentTrapCommunity));
	g_commonAgentTrap.commonAgentTrapCommunity_len = sizeof(g_commonAgentTrap.commonAgentTrapCommunity);
	g_commonAgentTrap.commonAgentTrapStatus = 1;

    reg =
        netsnmp_create_handler_registration("commonAgentTrapTable",
                                            commonAgentTrapTable_handler,
                                            commonAgentTrapTable_oid,
                                            commonAgentTrapTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: commonAgentTrapIndex */
                                     0);
    table_info->min_column = COLUMN_COMMONAGENTTRAPINDEX;
    table_info->max_column = COLUMN_COMMONAGENTTRAPSTATUS;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point =
        commonAgentTrapTable_get_first_data_point;
    iinfo->get_next_data_point = commonAgentTrapTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);
	netsnmp_inject_handler( reg,
				netsnmp_get_cache_handler(HC_CACHE_TIMEOUT,
						commonAgentTrapTable_load, commonAgentTrapTable_free,
						commonAgentTrapTable_oid, OID_LENGTH(commonAgentTrapTable_oid)));
		DEBUGMSGTL(("commonAgentTrapTable",
					"initialize commonAgentTrapTable\n"));  
    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct commonAgentTrapTable_entry {
    /*
     * Index values 
     */
    long            commonAgentTrapIndex;

    /*
     * Column values 
     */
    //long            commonAgentTrapIndex;
    in_addr_t       commonAgentTrapIP;
    in_addr_t       old_commonAgentTrapIP;
    char            commonAgentTrapCommunity[MAX_COMMUNITY_SIZE];
    size_t          commonAgentTrapCommunity_len;
    char            old_commonAgentTrapCommunity[MAX_COMMUNITY_SIZE];
    size_t          old_commonAgentTrapCommunity_len;
    long            commonAgentTrapStatus;
    long            old_commonAgentTrapStatus;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct commonAgentTrapTable_entry *next;
};

struct commonAgentTrapTable_entry *commonAgentTrapTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct commonAgentTrapTable_entry *
commonAgentTrapTable_createEntry(struct commonAgentTrapTable_entry *commonAgentTrap)
{
    struct commonAgentTrapTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct commonAgentTrapTable_entry);
    if (!entry)
        return NULL;

    //entry->commonAgentTrapIndex = commonAgentTrapIndex;
    memcpy(entry, commonAgentTrap, sizeof(*entry));
    entry->next = commonAgentTrapTable_head;
    commonAgentTrapTable_head = entry;
    return entry;
}

void commonAgentTrapTable_setEntry(
				struct commonAgentTrapTable_entry *entry, 
				snmp_commonAgentTrap_t *pinfo
				)
{

	memset(entry, 0, sizeof(*entry));
	
	entry->commonAgentTrapIndex = pinfo->commonAgentTrapIndex;
	entry->commonAgentTrapIP = pinfo->commonAgentTrapIP;
	strncpy(entry->commonAgentTrapCommunity, pinfo->commonAgentTrapCommunity, sizeof(entry->commonAgentTrapCommunity));
	entry->commonAgentTrapCommunity_len = pinfo->commonAgentTrapCommunity_len;
	entry->commonAgentTrapStatus =pinfo->commonAgentTrapStatus;
}


/*
 * remove a row from the table 
 */
void
commonAgentTrapTable_removeEntry(struct commonAgentTrapTable_entry *entry)
{
    struct commonAgentTrapTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = commonAgentTrapTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        commonAgentTrapTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}

void commonAgentTrapTable_removeAllEntry(void )
{
    struct commonAgentTrapTable_entry *ptr, *pnext;

    for (ptr = commonAgentTrapTable_head; ptr != NULL; ptr = pnext) {
		 pnext = ptr->next;
		 SNMP_FREE(ptr); 
    }
	commonAgentTrapTable_head = NULL;
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
commonAgentTrapTable_get_first_data_point(void **my_loop_context,
                                          void **my_data_context,
                                          netsnmp_variable_list *
                                          put_index_data,
                                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = commonAgentTrapTable_head;
    return commonAgentTrapTable_get_next_data_point(my_loop_context,
                                                    my_data_context,
                                                    put_index_data,
                                                    mydata);
}

netsnmp_variable_list *
commonAgentTrapTable_get_next_data_point(void **my_loop_context,
                                         void **my_data_context,
                                         netsnmp_variable_list *
                                         put_index_data,
                                         netsnmp_iterator_info *mydata)
{
    struct commonAgentTrapTable_entry *entry =
        (struct commonAgentTrapTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->commonAgentTrapIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the commonAgentTrapTable table */
int
commonAgentTrapTable_handler(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *reqinfo,
                             netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct commonAgentTrapTable_entry *table_entry;
	int ret = 0;
	ipc_sys_snmp_ack_t *pack = NULL;
	ipc_sys_snmp_ack_t *pack_send = NULL;
	sys_snmp_t pinfo;
	u_char buf[MAX_COMMUNITY_SIZE+1] = {0};
	int i = 0;
	memset(&pinfo, 0, sizeof(sys_snmp_t));
    DEBUGMSGTL(("commonAgentTrapTable:handler",
                "Processing request (%d)\n", reqinfo->mode));
    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct commonAgentTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_COMMONAGENTTRAPINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->commonAgentTrapIndex);
                break;
            case COLUMN_COMMONAGENTTRAPIP:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb,
                                           ASN_IPADDRESS,
                                           table_entry->commonAgentTrapIP);
                break;
            case COLUMN_COMMONAGENTTRAPCOMMUNITY:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->commonAgentTrapCommunity,
                                         strlen(table_entry->commonAgentTrapCommunity));
                break;
            case COLUMN_COMMONAGENTTRAPSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->commonAgentTrapStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct commonAgentTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_COMMONAGENTTRAPIP:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                //ret = netsnmp_check_vb_int(request->requestvb);
				ret = netsnmp_check_vb_type(request->requestvb, ASN_IPADDRESS);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_COMMONAGENTTRAPCOMMUNITY:
                /*
                 * or possibly 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->commonAgentTrapCommunity));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_COMMONAGENTTRAPSTATUS:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
		pack = ipc_sys_snmp(ipc_fd, IPC_CONFIG_GET, IPC_APPLY_NONE, NULL);
		if(pack && pack->hdr.status == IPC_STATUS_OK) 
		{		
			memcpy(&pinfo, &pack->snmp, sizeof(sys_snmp_t));
			if(pack)
			{
				free(pack);
			}
		}
		else
		{	
			if(pack)
			{
				free(pack);
			}
			return SNMP_ERR_GENERR;
		}
        for (request = requests; request; request = request->next) {
            table_entry = (struct commonAgentTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_COMMONAGENTTRAPIP:
                table_entry->old_commonAgentTrapIP =
                    table_entry->commonAgentTrapIP;
                table_entry->commonAgentTrapIP =
                    *request->requestvb->val.integer;
				
				pinfo.snmp_trap_ip.s_addr = table_entry->commonAgentTrapIP;
				pinfo.snmp_set_flag = 0;		
				pinfo.snmp_set_flag |= (SNMP_TRAP_FLAG | DONT_TRIGER_SIGNAL);
				pack_send = ipc_sys_snmp(ipc_fd, IPC_CONFIG_SET, IPC_APPLY_NOW /*| IPC_APPLY_COMMIT*/, &pinfo);
				if(pack_send)
			    {
			    	free(pack_send);
			    }
				ret = ipc_system_request(IPC_SYS_NVRAM_COMMIT);
				if(IPC_STATUS_OK != ret)
			    {
			        printf("System running config saved to flash memory failed!");	   
				}
                break;
            case COLUMN_COMMONAGENTTRAPCOMMUNITY:
                memcpy(table_entry->old_commonAgentTrapCommunity,
                       table_entry->commonAgentTrapCommunity,
                       sizeof(table_entry->commonAgentTrapCommunity));
                table_entry->old_commonAgentTrapCommunity_len =
                    table_entry->commonAgentTrapCommunity_len;
                memset(table_entry->commonAgentTrapCommunity, 0,
                       sizeof(table_entry->commonAgentTrapCommunity));
				if(0 == request->requestvb->val_len)
				{
					return SNMP_ERR_BADVALUE;
				}
				else
				{
            	    memcpy(table_entry->commonAgentTrapCommunity,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
				}
				memcpy(buf,request->requestvb->val.string,
                       request->requestvb->val_len);
				for(i=0; i<request->requestvb->val_len; i++)
				{	
					if(buf)
					{
						if((buf[i] < 0x20) || (buf[i] > 0x7e) || (buf[i] == '\\') || 
						 (buf[i] == '\/') || (buf[i] == '\"')  || (buf[i] == '\'') ||
						 (buf[i] == '\;') || (buf[i] == '#') || ((0 == i) && (buf[i] == ' ')))
						{
							DEBUGMSGTL(("system_mib","invaid value=0x%02x\n", buf[i]));
							return SNMP_ERR_BADVALUE;
						}
					}
				}
                table_entry->commonAgentTrapCommunity_len =
                    request->requestvb->val_len;
				memset(pinfo.snmp_trap_community, 0, sizeof(pinfo.snmp_trap_community));
				strncpy(pinfo.snmp_trap_community, table_entry->commonAgentTrapCommunity, request->requestvb->val_len);
				pinfo.snmp_set_flag = 0;		
			
				pinfo.snmp_set_flag |= (SNMP_TRAP_FLAG | DONT_TRIGER_SIGNAL);
				pack_send = ipc_sys_snmp(ipc_fd, IPC_CONFIG_SET, IPC_APPLY_NOW /*| IPC_APPLY_COMMIT*/, &pinfo);
				if(pack_send)
			    {
			    	free(pack_send);
			    }
				ret = ipc_system_request(IPC_SYS_NVRAM_COMMIT);
				if(IPC_STATUS_OK != ret)
			    {
			        printf("System running config saved to flash memory failed!");	   
				}
                break;
            case COLUMN_COMMONAGENTTRAPSTATUS:
                table_entry->old_commonAgentTrapStatus =
                    table_entry->commonAgentTrapStatus;
                table_entry->commonAgentTrapStatus =
                    *request->requestvb->val.integer;
				if(2 == table_entry->commonAgentTrapStatus)
				{
					pinfo.snmp_trap_en = 0;
				}
				else if(1 == table_entry->commonAgentTrapStatus)
				{
					pinfo.snmp_trap_en = 1;
				}	
				pinfo.snmp_set_flag = 0;		
			
				pinfo.snmp_set_flag |= (SNMP_TRAP_FLAG | DONT_TRIGER_SIGNAL);

				pack_send = ipc_sys_snmp(ipc_fd, IPC_CONFIG_SET, IPC_APPLY_NOW /*| IPC_APPLY_COMMIT*/, &pinfo);
				if(pack_send)
			    {
			    	free(pack_send);
			    }
				ret = ipc_system_request(IPC_SYS_NVRAM_COMMIT);
				if(IPC_STATUS_OK != ret)
			    {
			        printf("System running config saved to flash memory failed!");	   
				}
                break;
            }
        }	
		reconfig = 1;
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct commonAgentTrapTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            switch (table_info->colnum) {
            case COLUMN_COMMONAGENTTRAPIP:
                table_entry->commonAgentTrapIP =
                    table_entry->old_commonAgentTrapIP;
                table_entry->old_commonAgentTrapIP = 0;
                break;
            case COLUMN_COMMONAGENTTRAPCOMMUNITY:
                memcpy(table_entry->commonAgentTrapCommunity,
                       table_entry->old_commonAgentTrapCommunity,
                       sizeof(table_entry->commonAgentTrapCommunity));
                memset(table_entry->old_commonAgentTrapCommunity, 0,
                       sizeof(table_entry->commonAgentTrapCommunity));
                table_entry->commonAgentTrapCommunity_len =
                    table_entry->old_commonAgentTrapCommunity_len;
                break;
            case COLUMN_COMMONAGENTTRAPSTATUS:
                table_entry->commonAgentTrapStatus =
                    table_entry->old_commonAgentTrapStatus;
                table_entry->old_commonAgentTrapStatus = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:			
		
        break;
    }
    return SNMP_ERR_NOERROR;
}

int commonAgentTrapTable_load(netsnmp_cache *cache, void *vmagic)
{
	struct commonAgentTrapTable_entry entry;
	int ret = 0;
	sys_snmp_t pinfo;
	snmp_commonAgentTrap_t *info = NULL;

	/* Free All */
	commonAgentTrapTable_removeAllEntry();
	info = &g_commonAgentTrap;

	#ifdef CONFIG_CATVCOM
	ipc_sys_snmp_ack_t *pack = NULL;
	memset(&pinfo, 0, sizeof(sys_snmp_t));
	pack = ipc_sys_snmp(ipc_fd, IPC_CONFIG_GET, IPC_APPLY_NONE, NULL);
	if(pack && pack->hdr.status == IPC_STATUS_OK) 
	{		
		memcpy(&pinfo, &pack->snmp, sizeof(sys_snmp_t));
		info->commonAgentTrapIP = pinfo.snmp_trap_ip.s_addr;

		memcpy(info->commonAgentTrapCommunity, pinfo.snmp_trap_community, sizeof(info->commonAgentTrapCommunity));
		if(0 == pinfo.snmp_trap_en)
		{
			info->commonAgentTrapStatus = 2;
		}
		else
		{
			info->commonAgentTrapStatus = 1;
		}
		if(pack)
		{
			free(pack);
		}
	}
	else
	{	
		if(pack)
		{
			free(pack);
		}
		return SNMP_ERR_GENERR;
	}
	#endif
	int TrapTable_num = 0;
	int i = 0;
	TrapTable_num = 1;
	for(i = 0; i < TrapTable_num; i++)
	{
		commonAgentTrapTable_setEntry(&entry, &info[i]);	
		commonAgentTrapTable_createEntry(&entry);	
	}
safe_exit:
	
	HC_IPC_ASSERT(ret);
	
    return ret; 
} 


void commonAgentTrapTable_free(netsnmp_cache *cache, void *magic)
{
	DEBUGMSGTL(("commonAgentTrapTable", "Free commonAgentTrapTable Group\n"));  
}

