/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef COMMONDEVICENUM_H
#define COMMONDEVICENUM_H
config_add_mib(EPN104ZG-MIB-V1)
config_require(util_funcs/header_generic)
config_require(EPN104/commonDeviceNum)

/*
 * function declarations 
 */
void            init_commonDeviceNum(void);
Netsnmp_Node_Handler handle_commonDeviceNum;
extern void init_ipc_connect(void);

#endif                          /* COMMONDEVICENUM_H */
