/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef ZGNETWROKINFO_H
#define ZGNETWROKINFO_H
config_add_mib(EPN104ZG-MIB-V1)
config_require(util_funcs/header_generic)
config_require(EPN104/zgNetwrokInfo)

/*
 * function declarations 
 */
void            init_zgNetwrokInfo(void);
Netsnmp_Node_Handler handle_zgIpAddress;
Netsnmp_Node_Handler handle_zgIpMask;
Netsnmp_Node_Handler handle_zgIpGateway;
Netsnmp_Node_Handler handle_zgIpPhysicalAddress;
Netsnmp_Node_Handler handle_zgIpFind;

#endif                          /* ZGNETWROKINFO_H */
