/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef ZGSYSTEMINFO_H
#define ZGSYSTEMINFO_H
config_add_mib(EPN104ZG-MIB-V1)
config_require(util_funcs/header_generic)
config_require(EPN104/zgSystemInfo)

/*
 * function declarations 
 */
void            init_zgSystemInfo(void);
Netsnmp_Node_Handler handle_zgsystemGUIType;

#define MAX_SYSTEMINFO_SIZE  64

#endif                          /* ZGSYSTEMINFO_H */
