/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cltConfigCableScalar.h"

#include "ipc_interfaceTC.h"

#ifndef DBGID
#define DBGID  "hc:cltcable"
#endif

#ifndef DBGID
#define DBGID "defalut"
#endif 


/** Initializes the cltConfigCableScalar module */
void
init_cltConfigCableScalar(void)
{
    static oid      cltConfigCableNumber_oid[] =
        { 1, 3, 6, 1, 4, 1, 36368, 1, 1, 1, 1, 2, 4, 1, 1 };

    DEBUGMSGTL((DBGID, "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("cltConfigCableNumber",
                             handle_cltConfigCableNumber,
                             cltConfigCableNumber_oid,
                             OID_LENGTH(cltConfigCableNumber_oid),
                             HANDLER_CAN_RONLY));
}

int
handle_cltConfigCableNumber(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
	int value = HC_CABLE_NUM;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&value
                                 /* XXX: a pointer to the scalar's data */
                                 ,
                                sizeof(value) /*
                                  * XXX: the length of the data in bytes 
                                  */ );
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_cltConfigCableNumber\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
