/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cltConfigVLANTrunkTable.h"

#include "ipc_interfaceTC.h"

#undef DBGID
#define DBGID  "hc:clttrunktable"

#ifndef DBGID
#define DBGID "defalut"
#endif 


LOCAL_COMMIT_DECLARE();

#define local_commit()  LOCAL_COMMIT(500, cltConfigVLANTrunkTable_commit, NULL)


/** Initializes the cltConfigVLANTrunkTable module */
void
init_cltConfigVLANTrunkTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_cltConfigVLANTrunkTable();
}

//# Determine the first/last column names

/** Initialize the cltConfigVLANTrunkTable table by defining its contents and how it's structured */
void
initialize_table_cltConfigVLANTrunkTable(void)
{
    static oid      cltConfigVLANTrunkTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 36368, 1, 1, 1, 1, 2, 3, 5 };
    size_t          cltConfigVLANTrunkTable_oid_len =
        OID_LENGTH(cltConfigVLANTrunkTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

	DEBUGMSGTL((DBGID, "Initializing\n"));

    reg =
        netsnmp_create_handler_registration("cltConfigVLANTrunkTable",
                                            cltConfigVLANTrunkTable_handler,
                                            cltConfigVLANTrunkTable_oid,
                                            cltConfigVLANTrunkTable_oid_len,
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: cltConfigVLANTrunkIndex */
                                     0);
    table_info->min_column = COLUMN_CLTCONFIGVLANTRUNKINDEX;
    table_info->max_column = COLUMN_CLTCONFIGVLANTRUNKROWSTATUS;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point =
        cltConfigVLANTrunkTable_get_first_data_point;
    iinfo->get_next_data_point =
        cltConfigVLANTrunkTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    netsnmp_inject_handler( reg,
		    netsnmp_get_cache_handler(HC_CACHE_TIMEOUT,
			   		cltConfigVLANTrunkTable_load, cltConfigVLANTrunkTable_free,
					cltConfigVLANTrunkTable_oid, OID_LENGTH(cltConfigVLANTrunkTable_oid)));
    DEBUGMSGTL((DBGID,
                "initialize cltConfigVLANTrunkTable\n"));     

    /*
     * Initialise the contents of the table here 
     */
}

    /*
     * Typical data structure for a row entry 
     */
struct cltConfigVLANTrunkTable_entry {
    /*
     * Index values 
     */
    long            cltConfigVLANTrunkIndex;

    /*
     * Column values 
     */
//    long            cltConfigVLANTrunkIndex;
    long            cltConfigVLANTrunkPortID;
    char            cltConfigVLANTrunkPortName[HC_IFNAME_SIZE];
    size_t          cltConfigVLANTrunkPortName_len;
    long            cltConfigVLANTrunkPVID;
    long            old_cltConfigVLANTrunkPVID;
    char            cltConfigVLANTrunkAllowed[1];
    size_t          cltConfigVLANTrunkAllowed_len;
    char            old_cltConfigVLANTrunkAllowed[1];
    size_t          old_cltConfigVLANTrunkAllowed_len;
    long            cltConfigVLANTrunkRowStatus;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct cltConfigVLANTrunkTable_entry *next;
};

struct cltConfigVLANTrunkTable_entry *cltConfigVLANTrunkTable_head;
struct cltConfigVLANTrunkTable_entry *cltConfigVLANTrunkTable_commit_head;

/*
 * create a new row in the (unsorted) table 
 */
struct cltConfigVLANTrunkTable_entry *
cltConfigVLANTrunkTable_createEntry(long cltConfigVLANTrunkIndex,
		struct cltConfigVLANTrunkTable_entry *cltConfigVLANTrunkTable)
{
    struct cltConfigVLANTrunkTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct cltConfigVLANTrunkTable_entry);
    if (!entry)
        return NULL;

	memcpy(entry, cltConfigVLANTrunkTable, sizeof(*entry));

    entry->cltConfigVLANTrunkIndex = cltConfigVLANTrunkIndex;
    entry->next = cltConfigVLANTrunkTable_head;
    cltConfigVLANTrunkTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
cltConfigVLANTrunkTable_removeEntry(struct cltConfigVLANTrunkTable_entry
                                    *entry)
{
    struct cltConfigVLANTrunkTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = cltConfigVLANTrunkTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        cltConfigVLANTrunkTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


void cltConfigVLANTrunkTable_removeAllEntry(void )
{
    struct cltConfigVLANTrunkTable_entry *ptr, *pnext;

    for (ptr = cltConfigVLANTrunkTable_head; ptr != NULL; ptr = pnext) {
		 pnext = ptr->next;
		 SNMP_FREE(ptr); 
    }
	cltConfigVLANTrunkTable_head = NULL;
}



void cltConfigVLANTrunkTable_setEntry(
				struct cltConfigVLANTrunkTable_entry *entry, 
				int portid,
				char* portname,
				int pvid,
				int inservice
				)
{
	entry->cltConfigVLANTrunkPortID = portid;
	safe_strncpy(entry->cltConfigVLANTrunkPortName, portname, sizeof(entry->cltConfigVLANTrunkPortName));
	entry->cltConfigVLANTrunkPortName_len = strlen(entry->cltConfigVLANTrunkPortName);
	entry->cltConfigVLANTrunkPVID = pvid; 
	entry->cltConfigVLANTrunkRowStatus = inservice ? RowStatus_active : RowStatus_notInService;
	entry->cltConfigVLANTrunkAllowed[0] = 0;
	entry->cltConfigVLANTrunkAllowed_len = 0;
	
}


struct cltConfigVLANTrunkTable_entry *
cltConfigVLANTrunkTable_backupCommitEntry(
				struct cltConfigVLANTrunkTable_entry *cltConfigVLANTrunkTable)
{
    struct cltConfigVLANTrunkTable_entry *entry, *next;

    for (entry = cltConfigVLANTrunkTable_commit_head; entry != NULL; entry = entry->next) {
		if (entry->cltConfigVLANTrunkIndex == cltConfigVLANTrunkTable->cltConfigVLANTrunkIndex){
			break;
		}		
    }	

	if (!entry){
		entry = SNMP_MALLOC_TYPEDEF(struct cltConfigVLANTrunkTable_entry);
		if (!entry)
			return NULL;
		entry->next = cltConfigVLANTrunkTable_commit_head;
		cltConfigVLANTrunkTable_commit_head = entry;
	}

	
	next = entry->next;
	memcpy(entry, cltConfigVLANTrunkTable, sizeof(*entry));
	entry->next = next;
	
    return entry;	
}


void cltConfigVLANTrunkTable_removeAllCommitEntry(void )
{
    struct cltConfigVLANTrunkTable_entry *ptr, *pnext;

    for (ptr = cltConfigVLANTrunkTable_commit_head; ptr != NULL; ptr = pnext) {
		 pnext = ptr->next;
		 SNMP_FREE(ptr); 
    }
	cltConfigVLANTrunkTable_commit_head = NULL;
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
cltConfigVLANTrunkTable_get_first_data_point(void **my_loop_context,
                                             void **my_data_context,
                                             netsnmp_variable_list *
                                             put_index_data,
                                             netsnmp_iterator_info *mydata)
{
    *my_loop_context = cltConfigVLANTrunkTable_head;
    return cltConfigVLANTrunkTable_get_next_data_point(my_loop_context,
                                                       my_data_context,
                                                       put_index_data,
                                                       mydata);
}

netsnmp_variable_list *
cltConfigVLANTrunkTable_get_next_data_point(void **my_loop_context,
                                            void **my_data_context,
                                            netsnmp_variable_list *
                                            put_index_data,
                                            netsnmp_iterator_info *mydata)
{
    struct cltConfigVLANTrunkTable_entry *entry =
        (struct cltConfigVLANTrunkTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->cltConfigVLANTrunkIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the cltConfigVLANTrunkTable table */
int
cltConfigVLANTrunkTable_handler(netsnmp_mib_handler *handler,
                                netsnmp_handler_registration *reginfo,
                                netsnmp_agent_request_info *reqinfo,
                                netsnmp_request_info *requests)
{
	int ret;
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct cltConfigVLANTrunkTable_entry *table_entry;
	netsnmp_variable_list *requestvb;	

    if (((reqinfo->mode == MODE_GET) || (reqinfo->mode == MODE_SET_ACTION)) 
		&& !netsnmp_cache_is_valid(reqinfo, reginfo->handlerName)) {
        netsnmp_assert(!"cache == valid"); /* always false */
        cltConfigVLANTrunkTable_load( NULL, NULL );	/* XXX - check for failure */
    }

    DEBUGMSGTL((DBGID, "Handler - mode %s\n",
                    se_find_label_in_slist("agent_mode", reqinfo->mode)));


    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct cltConfigVLANTrunkTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);
			requestvb = request->requestvb;
			HC_DBG_OID(requestvb);	

            switch (table_info->colnum) {
            case COLUMN_CLTCONFIGVLANTRUNKINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltConfigVLANTrunkIndex);
                break;
            case COLUMN_CLTCONFIGVLANTRUNKPORTID:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltConfigVLANTrunkPortID);
                break;
            case COLUMN_CLTCONFIGVLANTRUNKPORTNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cltConfigVLANTrunkPortName,
                                         table_entry->
                                         cltConfigVLANTrunkPortName_len);
                break;
            case COLUMN_CLTCONFIGVLANTRUNKPVID:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltConfigVLANTrunkPVID);
                break;
            case COLUMN_CLTCONFIGVLANTRUNKALLOWED:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cltConfigVLANTrunkAllowed,
                                         table_entry->
                                         cltConfigVLANTrunkAllowed_len);
                break;
            case COLUMN_CLTCONFIGVLANTRUNKROWSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltConfigVLANTrunkRowStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_entry = (struct cltConfigVLANTrunkTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);
			requestvb = request->requestvb;
			HC_DBG_OID(requestvb);	

            switch (table_info->colnum) {
            case COLUMN_CLTCONFIGVLANTRUNKPVID:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
				if (vlan_in_transparent_mode() ||!vlan_exist(vb_int(request->requestvb), NULL)){
                    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
                    return SNMP_ERR_NOERROR;						
				}
				
                break;
            case COLUMN_CLTCONFIGVLANTRUNKALLOWED:
                /*
                 * or possiblc 'netsnmp_check_vb_type_and_size' 
                
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              cltConfigVLANTrunkAllowed));
                if (ret != SNMP_ERR_NOERROR)  {*/
                    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
                    return SNMP_ERR_NOERROR;
              //  }
                break;
            case COLUMN_CLTCONFIGVLANTRUNKROWSTATUS:
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
				if (!validRowStatus(vb_int(request->requestvb)) 
					&& ((vb_int(request->requestvb) == RowStatus_active) 
					|| (vb_int(request->requestvb) == RowStatus_notInService)) ){
                    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
                    return SNMP_ERR_NOERROR;						
				}

				
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_entry = (struct cltConfigVLANTrunkTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);
			requestvb = request->requestvb;
			HC_DBG_OID(requestvb);	

            switch (table_info->colnum) {
            case COLUMN_CLTCONFIGVLANTRUNKPVID:
                table_entry->old_cltConfigVLANTrunkPVID =
                    table_entry->cltConfigVLANTrunkPVID;
                table_entry->cltConfigVLANTrunkPVID =
                    *request->requestvb->val.integer;
                break;
            case COLUMN_CLTCONFIGVLANTRUNKALLOWED:
				/*
                memcpy(table_entry->old_cltConfigVLANTrunkAllowed,
                       table_entry->cltConfigVLANTrunkAllowed,
                       sizeof(table_entry->cltConfigVLANTrunkAllowed));
                table_entry->old_cltConfigVLANTrunkAllowed_len =
                    table_entry->cltConfigVLANTrunkAllowed_len;
                memset(table_entry->cltConfigVLANTrunkAllowed, 0,
                       sizeof(table_entry->cltConfigVLANTrunkAllowed));
                memcpy(table_entry->cltConfigVLANTrunkAllowed,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->cltConfigVLANTrunkAllowed_len =
                    request->requestvb->val_len;*/
                break;
			case COLUMN_CLTCONFIGVLANTRUNKROWSTATUS:
                table_entry->cltConfigVLANTrunkRowStatus =
                    *request->requestvb->val.integer;

				break;
            }
			cltConfigVLANTrunkTable_backupCommitEntry(table_entry);
        }

        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_entry = (struct cltConfigVLANTrunkTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);
			requestvb = request->requestvb;
			HC_DBG_OID(requestvb);	

            switch (table_info->colnum) {
            case COLUMN_CLTCONFIGVLANTRUNKPVID:
                table_entry->cltConfigVLANTrunkPVID =
                    table_entry->old_cltConfigVLANTrunkPVID;
                table_entry->old_cltConfigVLANTrunkPVID = 0;
                break;
            case COLUMN_CLTCONFIGVLANTRUNKALLOWED:
				/*
                memcpy(table_entry->cltConfigVLANTrunkAllowed,
                       table_entry->old_cltConfigVLANTrunkAllowed,
                       sizeof(table_entry->cltConfigVLANTrunkAllowed));
                memset(table_entry->old_cltConfigVLANTrunkAllowed, 0,
                       sizeof(table_entry->cltConfigVLANTrunkAllowed));
                table_entry->cltConfigVLANTrunkAllowed_len =
                    table_entry->old_cltConfigVLANTrunkAllowed_len;*/
                break;
            case COLUMN_CLTCONFIGVLANTRUNKROWSTATUS:
 
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
		local_commit();
        break;
    }
    return SNMP_ERR_NOERROR;
}


int cltConfigVLANTrunkTable_load(netsnmp_cache *cache, void *vmagic)
{
	int ret, i;
	char *show_if[] = {VLAN_IFLIST, NULL};
	
	struct cltConfigVLANTrunkTable_entry entry;
	switch_vlan_interface_t *vlanif;
	
		
	ret = vlan_interface_update();
	
    if (HC_IPC_ERROR(ret)) {
		CLR_VALID();
		DEBUGMSGTL((DBGID, "Failed to load cltConfigVLANTrunkTable Group\n"));
    } else {
		SET_VALID();
        DEBUGMSGTL((DBGID, "Loaded cltConfigVLANTrunkTable Group\n"));
    }

	HC_IPC_ASSERT(ret);

	if (sys_vlan_mode.mode == VLAN_MODE_8021Q){
		for (i = 0; show_if[i]; i ++){
			vlanif = dot1q_vlanif_search(show_if[i]);
			if (vlanif){
				cltConfigVLANTrunkTable_setEntry(&entry, i  + 1,
						interface_fancy_name(show_if[i]), 
						vlanif->pvid, 
						(vlanif->mode == ETH_SWITCHPORT_TRUNK) ? 1 : 0);
				cltConfigVLANTrunkTable_createEntry(i, &entry);
			}
		}
	}else {
		for (i = 0; show_if[i]; i ++){
			cltConfigVLANTrunkTable_setEntry(&entry, i	+ 1,
					interface_fancy_name(show_if[i]), 
					1, 
					(transparent_vlanif_search(show_if[i]) == ETH_SWITCHPORT_TRUNK) ? 1 : 0);
			cltConfigVLANTrunkTable_createEntry(i, &entry);
		}
	}

    return ret; 	
} 

void cltConfigVLANTrunkTable_free(netsnmp_cache *cache, void *magic)
{
	DEBUGMSGTL((DBGID, "Free cltConfigVLANTrunkTable Group\n"));  
	
	cltConfigVLANTrunkTable_removeAllEntry();
}


void cltConfigVLANTrunkTable_commit(unsigned int regNo, void *clientargs)
{
	int i, ifid, changed = 0, ret, ifmode;
	char *show_if[] = {VLAN_IFLIST, NULL};
	struct cltConfigVLANTrunkTable_entry *ptr;
	switch_vlan_interface_t *vlanif[MAX_CLT_ETH_PORTS], *vi, *v;
	int vlanif_size, vlanif_cnt;
	
	if (sys_vlan_mode.mode == VLAN_MODE_TRANSPARENT){
		for (ptr = cltConfigVLANTrunkTable_commit_head; ptr != NULL; ptr = ptr->next){
			ifid = ptr->cltConfigVLANTrunkIndex - 1;
			transparent_vlanif_set(show_if[ifid], 
				(ptr->cltConfigVLANTrunkRowStatus == RowStatus_active) ? ETH_SWITCHPORT_TRUNK : ETH_SWITCHPORT_ACCESS);
			changed = 1;
		}
		cltConfigVLANTrunkTable_removeAllCommitEntry();		
		if (changed){
			ret = ipc_set_vlan_mode(&sys_vlan_mode);
			if (HC_IPC_ERROR(ret)){
				DEBUGMSGTL((DBGID, "Failed to commit cltConfigVLANTrunkTable Group\n"));
			} else {
				DEBUGMSGTL((DBGID, "Commited cltConfigVLANTrunkTable Group\n"));
			}
			HC_IPC_ASSERT1(ret);
		}	
		return;
	}
	// 802.1q

	memset(vlanif, 0, sizeof(vlanif));
	vlanif_size = 0;
	vlanif_cnt = 0;
	for (ptr = cltConfigVLANTrunkTable_commit_head; ptr != NULL; ptr = ptr->next){
		ifid = ptr->cltConfigVLANTrunkIndex - 1;
		vlanif[ifid] = dot1q_vlanif_dup(show_if[ifid]);
		if (vlanif[ifid]){
			vlanif[ifid]->pvid = ptr->cltConfigVLANTrunkPVID;
			ifmode = (ptr->cltConfigVLANTrunkRowStatus == RowStatus_active) ? ETH_SWITCHPORT_TRUNK : ETH_SWITCHPORT_ACCESS;
			if (ifmode != vlanif[ifid]->mode){
				vlanif[ifid]->count = 0;
			}
			vlanif_cnt ++;			
			vlanif_size += sizeof_vlan_interface(vlanif[ifid]->trunk_hybrid, vlanif[ifid]->count);
		}
	}
	cltConfigVLANTrunkTable_removeAllCommitEntry();	

	if ((vlanif_size > 0) && (vlanif_cnt > 0)){
		vi = (switch_vlan_interface_t *)malloc(vlanif_size);

		if (vi == NULL){
			for (i = 0; i < MAX_CLT_ETH_PORTS; i ++){
				if (vlanif[i]){
					free(vlanif[i]);
				}
			}
			HC_NOMEM_ASSERT1(vi);
		}
		v = vi;
		for (i = 0; i < MAX_CLT_ETH_PORTS; i ++){
			if (vlanif[i]){
				memcpy(v, vlanif[i], sizeof_vlan_interface(vlanif[i]->trunk_hybrid,vlanif[i]->count));
				v = vlan_interface_to_next(v);
			}
		}
		// free all vlanif 
		for (i = 0; i < MAX_CLT_ETH_PORTS; i ++){
			if (vlanif[i]){
				free(vlanif[i]);
			}
		}
		// commit all
		ret = ipc_set_vlan_interface(vi, vlanif_cnt);

		free(vi);

		if (HC_IPC_ERROR(ret)){
			DEBUGMSGTL((DBGID, "Failed to commit cltConfigVLANTrunkTable Group\n"));
		} else {
			DEBUGMSGTL((DBGID, "Commited cltConfigVLANTrunkTable Group\n"));
		}
		HC_IPC_ASSERT1(ret);
	}
}


