/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cltDeviceModelTable.h"

#include "ipc_interfaceTC.h"

#ifndef DBGID
#define DBGID  "hc:cltdevtable"
#endif

#ifndef DBGID
#define DBGID "defalut"
#endif 


/** Initializes the cltDeviceModelTable module */
void
init_cltDeviceModelTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_cltDeviceModelTable();
}

//# Determine the first/last column names


/** Initialize the cltDeviceModelTable table by defining its contents and how it's structured */
void
initialize_table_cltDeviceModelTable(void)
{
    static oid      cltDeviceModelTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 36368, 1, 1, 1, 1, 4, 1 };
    size_t          cltDeviceModelTable_oid_len =
        OID_LENGTH(cltDeviceModelTable_oid);
    netsnmp_handler_registration *reg;
    netsnmp_iterator_info *iinfo;
    netsnmp_table_registration_info *table_info;

	DEBUGMSGTL((DBGID, "Initializing\n"));

    reg =
        netsnmp_create_handler_registration("cltDeviceModelTable",
                                            cltDeviceModelTable_handler,
                                            cltDeviceModelTable_oid,
                                            cltDeviceModelTable_oid_len,
                                            HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: cltDeviceModelIndex */
                                     0);
    table_info->min_column = COLUMN_CLTDEVICEMODELINDEX;
    table_info->max_column = COLUMN_CLTDEVICEMODELIFNUMBER;

    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    iinfo->get_first_data_point = cltDeviceModelTable_get_first_data_point;
    iinfo->get_next_data_point = cltDeviceModelTable_get_next_data_point;
    iinfo->table_reginfo = table_info;

    netsnmp_register_table_iterator(reg, iinfo);

    DEBUGMSGTL((DBGID,
                "initialize cltDeviceModelTable\n"));    

    /*
     * Initialise the contents of the table here 
     */
	cltDeviceModelTable_load();     
}

    /*
     * Typical data structure for a row entry 
     */
struct cltDeviceModelTable_entry {
    /*
     * Index values 
     */
    long            cltDeviceModelIndex;

    /*
     * Column values 
     */
//    long            cltDeviceModelIndex;
    char            cltDeviceModelName[HC_SYS_MODEL_SIZE];
    size_t          cltDeviceModelName_len;
    long            cltDeviceModelIfNumber;

    /*
     * Illustrate using a simple linked list 
     */
    int             valid;
    struct cltDeviceModelTable_entry *next;
};

struct cltDeviceModelTable_entry *cltDeviceModelTable_head;

/*
 * create a new row in the (unsorted) table 
 */
struct cltDeviceModelTable_entry *
cltDeviceModelTable_createEntry(long cltDeviceModelIndex,
		char *name, int ifnumber)
{
    struct cltDeviceModelTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct cltDeviceModelTable_entry);
    if (!entry)
        return NULL;

	strcpy(entry->cltDeviceModelName, name);
	entry->cltDeviceModelName_len = strlen(name);
	entry->cltDeviceModelIfNumber = ifnumber;

    entry->cltDeviceModelIndex = cltDeviceModelIndex;
    entry->next = cltDeviceModelTable_head;
    cltDeviceModelTable_head = entry;
    return entry;
}

/*
 * remove a row from the table 
 */
void
cltDeviceModelTable_removeEntry(struct cltDeviceModelTable_entry *entry)
{
    struct cltDeviceModelTable_entry *ptr, *prev;

    if (!entry)
        return;                 /* Nothing to remove */

    for (ptr = cltDeviceModelTable_head, prev = NULL;
         ptr != NULL; prev = ptr, ptr = ptr->next) {
        if (ptr == entry)
            break;
    }
    if (!ptr)
        return;                 /* Can't find it */

    if (prev == NULL)
        cltDeviceModelTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}


/*
 * Example iterator hook routines - using 'get_next' to do most of the work 
 */
netsnmp_variable_list *
cltDeviceModelTable_get_first_data_point(void **my_loop_context,
                                         void **my_data_context,
                                         netsnmp_variable_list *
                                         put_index_data,
                                         netsnmp_iterator_info *mydata)
{
    *my_loop_context = cltDeviceModelTable_head;
    return cltDeviceModelTable_get_next_data_point(my_loop_context,
                                                   my_data_context,
                                                   put_index_data, mydata);
}

netsnmp_variable_list *
cltDeviceModelTable_get_next_data_point(void **my_loop_context,
                                        void **my_data_context,
                                        netsnmp_variable_list *
                                        put_index_data,
                                        netsnmp_iterator_info *mydata)
{
    struct cltDeviceModelTable_entry *entry =
        (struct cltDeviceModelTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if (entry) {
        snmp_set_var_typed_integer(idx, ASN_INTEGER,
                                   entry->cltDeviceModelIndex);
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the cltDeviceModelTable table */
int
cltDeviceModelTable_handler(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct cltDeviceModelTable_entry *table_entry;
	netsnmp_variable_list *requestvb;	

    DEBUGMSGTL((DBGID, "Handler - mode %s\n",
                    se_find_label_in_slist("agent_mode", reqinfo->mode)));


    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (struct cltDeviceModelTable_entry *)
                netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

			requestvb = request->requestvb;
			HC_DBG_OID(requestvb);		

            switch (table_info->colnum) {
            case COLUMN_CLTDEVICEMODELINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltDeviceModelIndex);
                break;
            case COLUMN_CLTDEVICEMODELNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cltDeviceModelName,
                                         table_entry->
                                         cltDeviceModelName_len);
                break;
            case COLUMN_CLTDEVICEMODELIFNUMBER:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cltDeviceModelIfNumber);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}


int cltDeviceModelTable_load(void)
{
	int ret, i;
	ret = supported_devices_update();
	HC_IPC_ASSERT(ret);
	for (i = 0; i < supported_devices_num; i ++){
		cltDeviceModelTable_createEntry(i + 1, supported_devices[i].alias, supported_devices[i].ports); 		
	}
	snmp_log(LOG_INFO, "cltDeviceModelTable load %d devices\n", supported_devices_num);
	return 0;
}






