/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef CLTNETWORKUNITUSERLISTTABLE_H
#define CLTNETWORKUNITUSERLISTTABLE_H

/*
 * function declarations 
 */
void            init_cltNetworkUnitUserListTable(void);
void            initialize_table_cltNetworkUnitUserListTable(void);
Netsnmp_Node_Handler cltNetworkUnitUserListTable_handler;
Netsnmp_First_Data_Point cltNetworkUnitUserListTable_get_first_data_point;
Netsnmp_Next_Data_Point cltNetworkUnitUserListTable_get_next_data_point;

NetsnmpCacheLoad         cltNetworkUnitUserListTable_load;
NetsnmpCacheFree         cltNetworkUnitUserListTable_free;
void cltNetworkUnitUserListTable_commit(unsigned int regNo, void *clientargs);

/*
 * column number definitions for table cltNetworkUnitUserListTable 
 */
#define COLUMN_CLTNETWORKUNITUSERLISTINDEX		1
#define COLUMN_CLTNETWORKUNITUSERLISTMACADDRESS		2
#define COLUMN_CLTNETWORKUNITUSERLISTDEVICEMODEL		3
#define COLUMN_CLTNETWORKUNITUSERLISTTEMPLATEID		4
#define COLUMN_CLTNETWORKUNITUSERLISTNAME		5
#define COLUMN_CLTNETWORKUNITUSERLISTDESCRIPTION		6
#define COLUMN_CLTNETWORKUNITUSERLISTROWSTATUS		7
#endif                          /* CLTNETWORKUNITUSERLISTTABLE_H */
