/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 40789 $
 * $Date: 2013-07-05 14:01:01 +0800 (Fri, 05 Jul 2013) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/rtl9601b/rtk_rtl9601b_table_struct.h>

#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_HSB_DATA_TABLE_FIELDS[] = 
{
    {   /* name     RTL9601B_HSB_DATA_TABLE_SPAtf */
        /* lsp */   561,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_15tf */
        /* lsp */   545,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_14tf */
        /* lsp */   529,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_13tf */
        /* lsp */   513,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_12tf */
        /* lsp */   497,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_11tf */
        /* lsp */   481,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_10tf */
        /* lsp */   465,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_9tf */
        /* lsp */   449,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_8tf */
        /* lsp */   433,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_7tf */
        /* lsp */   417,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_6tf */
        /* lsp */   401,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_5tf */
        /* lsp */   385,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_4tf */
        /* lsp */   369,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_3tf */
        /* lsp */   353,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_2tf */
        /* lsp */   337,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_1tf */
        /* lsp */   321,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_FIELD_0tf */
        /* lsp */   305,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_USER_VALIDtf */
        /* lsp */   289,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_ICMP_IFtf */
        /* lsp */   288,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_UDP_IFtf */
        /* lsp */   287,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_TCP_IFtf */
        /* lsp */   286,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_DIPtf */
        /* lsp */   254,
        /* len */   32,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_SIPtf */
        /* lsp */   222,
        /* len */   32,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_TOS_DSCPtf */
        /* lsp */   214,
        /* len */   8,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_IP_RSV_MC_ADDRtf */
        /* lsp */   213,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_IP_TYPEtf */
        /* lsp */   211,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_OMAPDUtf */
        /* lsp */   210,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_RLDP_IFtf */
        /* lsp */   211,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_LLC_OTHERtf */
        /* lsp */   209,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_PPPOE_IFtf */
        /* lsp */   208,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_SNAP_IFtf */
        /* lsp */   207,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_ETHER_TYPEtf */
        /* lsp */   191,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CTAGtf */
        /* lsp */   175,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CTAG_IFtf */
        /* lsp */   174,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_STAGtf */
        /* lsp */   158,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_STAG_IFtf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_TXPMSKtf */
        /* lsp */   149,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_PRISELtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_PRItf */
        /* lsp */   141,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_KEEPtf */
        /* lsp */   140,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_DISLRNtf */
        /* lsp */   138,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_PSELtf */
        /* lsp */   137,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_PON_SIDtf */
        /* lsp */   117,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_CPUTAG_IFtf */
        /* lsp */   116,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_SAtf */
        /* lsp */   68,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_DAtf */
        /* lsp */   20,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_PON_IDXtf */
        /* lsp */   14,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSB_DATA_TABLE_PKT_LENtf */
        /* lsp */   0,
        /* len */   14,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_HSA_DATA_NAT_FIELDS[] = 
{
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_ENDSCtf */
        /* lsp */   402,
        /* len */   13,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_BGDSCtf */
        /* lsp */   389,
        /* len */   13,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_QIDtf */
        /* lsp */   364,
        /* len */   25,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_FLOODPKTtf */
        /* lsp */   363,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_RESERVEtf */
        /* lsp */   353,
        /* len */   10,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_CPUPRItf */
        /* lsp */   350,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_FWDRSNtf */
        /* lsp */   342,
        /* len */   8,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_PON_SIDtf */
        /* lsp */   335,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_EXT_MASKtf */
        /* lsp */   329,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_DPMtf */
        /* lsp */   315,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_SPAtf */
        /* lsp */   312,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAB_PKTLENtf */
        /* lsp */   298,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_UNTAGSETtf */
        /* lsp */   291,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_CTAG_PONACTtf */
        /* lsp */   287,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_CTAG_ACTtf */
        /* lsp */   283,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_VIDZEROtf */
        /* lsp */   282,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_PRITAG_IFtf */
        /* lsp */   281,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_CTAG_IFtf */
        /* lsp */   280,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_PONVIDtf */
        /* lsp */   268,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_VIDtf */
        /* lsp */   256,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_CFItf */
        /* lsp */   255,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_PONPRItf */
        /* lsp */   252,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAC_PRItf */
        /* lsp */   249,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_STAG_IFtf */
        /* lsp */   248,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_DEItf */
        /* lsp */   247,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_UNTAGSETtf */
        /* lsp */   240,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_STAG_TYPEtf */
        /* lsp */   239,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_SP2Stf */
        /* lsp */   238,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_VIDSELtf */
        /* lsp */   237,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_FRCTAGtf */
        /* lsp */   236,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_FRCTAG_IFtf */
        /* lsp */   235,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_PONSVIDtf */
        /* lsp */   223,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_SVIDtf */
        /* lsp */   211,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_SVIDXtf */
        /* lsp */   205,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_PKT_SPRItf */
        /* lsp */   202,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_PONSPRItf */
        /* lsp */   199,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAS_SPRItf */
        /* lsp */   196,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAM_USER_PRItf */
        /* lsp */   175,
        /* len */   21,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAM_1P_REMtf */
        /* lsp */   172,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAM_1P_REM_ENtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAM_DSCP_REMtf */
        /* lsp */   165,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAM_DSCP_REM_ENtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_REGEN_CRCtf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_CPUKEEPtf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_KEEPtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_PTPtf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_TCPtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_UDPtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_IPV4tf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_IPV6tf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_RFC1042tf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAF_PPPOE_IFtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_L3Rtf */
        /* lsp */   153,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_ORGtf */
        /* lsp */   152,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_IPMCtf */
        /* lsp */   151,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_L2TRANStf */
        /* lsp */   150,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_L34TRANStf */
        /* lsp */   149,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_SRC_MODtf */
        /* lsp */   148,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_PPPOE_IDXtf */
        /* lsp */   145,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_PPPOE_ACTtf */
        /* lsp */   143,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_SMAC_IDXtf */
        /* lsp */   140,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_L3CKSUMtf */
        /* lsp */   124,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_L4CKSUMtf */
        /* lsp */   108,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_NEWIPtf */
        /* lsp */   76,
        /* len */   32,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_NEWPORTtf */
        /* lsp */   60,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_NEWDMACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_TTLM1_EXTMASKtf */
        /* lsp */   7,
        /* len */   5,
    },
    {   /* name     RTL9601B_HSA_DATA_NAT_RNG_NHSAN_TTLM1_PMASKtf */
        /* lsp */   0,
        /* len */   7,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_HSA_DATA_TABLE_FIELDS[] = 
{
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_ENDSCtf */
        /* lsp */   402,
        /* len */   13,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_BGDSCtf */
        /* lsp */   389,
        /* len */   13,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_QIDtf */
        /* lsp */   364,
        /* len */   25,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_FLOODPKTtf */
        /* lsp */   363,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_RESERVEtf */
        /* lsp */   353,
        /* len */   10,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_CPUPRItf */
        /* lsp */   350,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_FWDRSNtf */
        /* lsp */   342,
        /* len */   8,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_PON_SIDtf */
        /* lsp */   335,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_EXT_MASKtf */
        /* lsp */   329,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_DPMtf */
        /* lsp */   315,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_SPAtf */
        /* lsp */   312,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAB_PKTLENtf */
        /* lsp */   298,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_UNTAGSETtf */
        /* lsp */   291,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_CTAG_PONACTtf */
        /* lsp */   287,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_CTAG_ACTtf */
        /* lsp */   283,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_VIDZEROtf */
        /* lsp */   282,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_PRITAG_IFtf */
        /* lsp */   281,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_CTAG_IFtf */
        /* lsp */   280,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_PONVIDtf */
        /* lsp */   268,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_VIDtf */
        /* lsp */   256,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_CFItf */
        /* lsp */   255,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_PONPRItf */
        /* lsp */   252,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAC_PRItf */
        /* lsp */   249,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_STAG_IFtf */
        /* lsp */   248,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_DEItf */
        /* lsp */   247,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_UNTAGSETtf */
        /* lsp */   240,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_STAG_TYPEtf */
        /* lsp */   239,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_SP2Stf */
        /* lsp */   238,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_VIDSELtf */
        /* lsp */   237,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_FRCTAGtf */
        /* lsp */   236,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_FRCTAG_IFtf */
        /* lsp */   235,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_PONSVIDtf */
        /* lsp */   223,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_SVIDtf */
        /* lsp */   211,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_SVIDXtf */
        /* lsp */   205,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_PKT_SPRItf */
        /* lsp */   202,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_PONSPRItf */
        /* lsp */   199,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAS_SPRItf */
        /* lsp */   196,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAM_USER_PRItf */
        /* lsp */   175,
        /* len */   21,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAM_1P_REMtf */
        /* lsp */   172,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAM_1P_REM_ENtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REMtf */
        /* lsp */   165,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REM_ENtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_REGEN_CRCtf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_CPUKEEPtf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_KEEPtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_PTPtf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_TCPtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_UDPtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_IPV4tf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_IPV6tf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_RFC1042tf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAF_PPPOE_IFtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAP_PTP_RESVtf */
        /* lsp */   89,
        /* len */   65,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAP_PTP_IDtf */
        /* lsp */   82,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAP_PTP_ACTtf */
        /* lsp */   80,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAP_PTP_SECtf */
        /* lsp */   32,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSA_DATA_TABLE_RNG_NHSAP_PTP_NSECtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_ACL_ACTION_TABLE_FIELDS[] = 
{
    {   /* name     RTL9601B_ACL_ACTION_TABLE_HITtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_ACLINTtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_ACLPRItf */
        /* lsp */   16,
        /* len */   3,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_FWDACTtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_POLICACTtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_METER_IDXtf */
        /* lsp */   9,
        /* len */   4,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_RMK_DSCPtf */
        /* lsp */   3,
        /* len */   6,
    },
    {   /* name     RTL9601B_ACL_ACTION_TABLE_RMK_1Ptf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_ACL_DATA_FIELDS[] = 
{
    {   /* name     RTL9601B_ACL_DATA_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD7tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD6tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD5tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD4tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD3tf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD2tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_FIELD0tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_DATA_RSVtf */
        /* lsp */   12,
        /* len */   4,
    },
    {   /* name     RTL9601B_ACL_DATA_PMSKtf */
        /* lsp */   9,
        /* len */   3,
    },
    {   /* name     RTL9601B_ACL_DATA_TAGStf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     RTL9601B_ACL_DATA_TYPEtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_ACL_MASK_FIELDS[] = 
{
    {   /* name     RTL9601B_ACL_MASK_FIELD7tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD6tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD5tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD4tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD3tf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD2tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_FIELD0tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     RTL9601B_ACL_MASK_RSVtf */
        /* lsp */   12,
        /* len */   4,
    },
    {   /* name     RTL9601B_ACL_MASK_PMSKtf */
        /* lsp */   9,
        /* len */   3,
    },
    {   /* name     RTL9601B_ACL_MASK_TAGStf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     RTL9601B_ACL_MASK_TYPEtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_ACTION_DS_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_ACTION_DS_UNI_PMSKtf */
        /* lsp */   51,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_UNI_ACTtf */
        /* lsp */   49,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_DSCP_REMARKtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CF_PRItf */
        /* lsp */   45,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CFPRI_ACTtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CPRI_ACTtf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CVID_ACTtf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_C_PRItf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_C_VIDtf */
        /* lsp */   25,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CSPRI_ACTtf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CSVID_ACTtf */
        /* lsp */   21,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CS_PRItf */
        /* lsp */   18,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CS_VIDtf */
        /* lsp */   6,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CACTtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_DS_CSACTtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_ACTION_US_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_ACTION_US_DROPtf */
        /* lsp */   57,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_US_ASSIGN_IDXtf */
        /* lsp */   50,
        /* len */   7,
    },
    {   /* name     RTL9601B_CF_ACTION_US_SID_ACTtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_US_DSCP_REMARKtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CF_PRItf */
        /* lsp */   45,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CFPRI_ACTtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CPRI_ACTtf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CVID_ACTtf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_US_C_PRItf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_US_C_VIDtf */
        /* lsp */   25,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CSPRI_ACTtf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CSVID_ACTtf */
        /* lsp */   21,
        /* len */   2,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CS_PRItf */
        /* lsp */   18,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CS_VIDtf */
        /* lsp */   6,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CACTtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_ACTION_US_CSACTtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_MASK_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_MASK_ETH_TYPE_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_CF_MASK_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_TOS_GEMIDX_0tf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_MASK_L34_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_MASK_L34_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_INNER_TAGtf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_CF_MASK_L34_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_ACL_HITtf */
        /* lsp */   120,
        /* len */   7,
    },
    {   /* name     RTL9601B_CF_MASK_L34_DEItf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_L34_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_L34_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_L34_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_L34_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_L34_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_MASK_L34_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_MASK_L34_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_MASK_L34_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_RULE_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_RULE_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ETH_TYPE_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_CF_RULE_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_TOS_GEMIDX_0tf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_CF_RULE_ENHANCED_FIELDS[] = 
{
    {   /* name     RTL9601B_CF_RULE_ENHANCED_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_INNER_TAGtf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_ACL_HITtf */
        /* lsp */   120,
        /* len */   7,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_DEItf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     RTL9601B_CF_RULE_ENHANCED_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_L2_MC_DSL_FIELDS[] = 
{
    {   /* name     RTL9601B_L2_MC_DSL_VALIDtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_MC_DSL_MBRtf */
        /* lsp */   62,
        /* len */   3,
    },
    {   /* name     RTL9601B_L2_MC_DSL_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_MC_DSL_VID_FIDtf */
        /* lsp */   48,
        /* len */   12,
    },
    {   /* name     RTL9601B_L2_MC_DSL_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_L2_UC_FIELDS[] = 
{
    {   /* name     RTL9601B_L2_UC_VALIDtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_UC_STATICtf */
        /* lsp */   80,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_UC_CTAG_VIDtf */
        /* lsp */   68,
        /* len */   12,
    },
    {   /* name     RTL9601B_L2_UC_CTAG_IFtf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_UC_AGEtf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     RTL9601B_L2_UC_SPAtf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     RTL9601B_L2_UC_L2IVLtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_UC_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     RTL9601B_L2_UC_CVIDtf */
        /* lsp */   48,
        /* len */   12,
    },
    {   /* name     RTL9601B_L2_UC_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_L3_MC_DSL_FIELDS[] = 
{
    {   /* name     RTL9601B_L3_MC_DSL_VALIDtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     RTL9601B_L3_MC_DSL_MBRtf */
        /* lsp */   62,
        /* len */   3,
    },
    {   /* name     RTL9601B_L3_MC_DSL_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     RTL9601B_L3_MC_DSL_VIDtf */
        /* lsp */   28,
        /* len */   12,
    },
    {   /* name     RTL9601B_L3_MC_DSL_GIPtf */
        /* lsp */   0,
        /* len */   28,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_VLAN_FIELDS[] = 
{
    {   /* name     RTL9601B_VLAN_IVL_SVLtf */
        /* lsp */   7,
        /* len */   1,
    },
    {   /* name     RTL9601B_VLAN_ENSVLANHASHtf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     RTL9601B_VLAN_UNTAGtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     RTL9601B_VLAN_MBRtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_EPON_GRANT_FIELDS[] = 
{
    {   /* name     RTL9601B_EPON_GRANT_IS_FORCE_REPORTtf */
        /* lsp */   50,
        /* len */   1,
    },
    {   /* name     RTL9601B_EPON_GRANT_LLIDIDXtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     RTL9601B_EPON_GRANT_IS_DISCtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     RTL9601B_EPON_GRANT_GRANT_LENtf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     RTL9601B_EPON_GRANT_GRANT_STARTtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9601B)
rtk_tableField_t RTL9601B_HSA_DEBUG_DATA_FIELDS[] = 
{
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_RESERVED_02tf */
        /* lsp */   474,
        /* len */   38,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_EPtf */
        /* lsp */   471,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_DSL_VCtf */
        /* lsp */   467,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_34PPPOEtf */
        /* lsp */   451,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_34SMACtf */
        /* lsp */   403,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_RSV0tf */
        /* lsp */   397,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_TTLPMSKtf */
        /* lsp */   396,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_TTLEXMSKtf */
        /* lsp */   391,
        /* len */   5,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_NEWMACtf */
        /* lsp */   343,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_NEWPRTtf */
        /* lsp */   327,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_NEWIPtf */
        /* lsp */   295,
        /* len */   32,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_L4CKSUMtf */
        /* lsp */   279,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_L3CKSUMtf */
        /* lsp */   263,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_PPPOEACTtf */
        /* lsp */   261,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_SRC_MODtf */
        /* lsp */   260,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_L34TRANStf */
        /* lsp */   259,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_L2TRANStf */
        /* lsp */   258,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_ORGtf */
        /* lsp */   257,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA1_L3Rtf */
        /* lsp */   256,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_RESERVED_01tf */
        /* lsp */   232,
        /* len */   24,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_SV_DEItf */
        /* lsp */   231,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_STYPtf */
        /* lsp */   230,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PKTLEN_ORItf */
        /* lsp */   216,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_QIDtf */
        /* lsp */   209,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_STDSCtf */
        /* lsp */   196,
        /* len */   13,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CPUPRItf */
        /* lsp */   193,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_SPRItf */
        /* lsp */   190,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CORItf */
        /* lsp */   189,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CMDYtf */
        /* lsp */   188,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CRMStf */
        /* lsp */   187,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CINStf */
        /* lsp */   186,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CVIDtf */
        /* lsp */   174,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_RSV1tf */
        /* lsp */   172,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_CFItf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PTPNSECtf */
        /* lsp */   139,
        /* len */   32,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PTPSECtf */
        /* lsp */   91,
        /* len */   48,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PTPACTtf */
        /* lsp */   89,
        /* len */   2,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_REGENCRCtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PPPOEtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_RFC1042tf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_IPV6tf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_IPV4tf */
        /* lsp */   84,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PTPtf */
        /* lsp */   83,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_REMDSCP_PRItf */
        /* lsp */   77,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_REM1Q_PRItf */
        /* lsp */   74,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_REMDSCP_ENtf */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_REM1Q_ENtf */
        /* lsp */   72,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_SVIDtf */
        /* lsp */   60,
        /* len */   12,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_INSTAGtf */
        /* lsp */   59,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_INCTAGtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PKTLENtf */
        /* lsp */   44,
        /* len */   14,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_SPAtf */
        /* lsp */   41,
        /* len */   3,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_DPCtf */
        /* lsp */   37,
        /* len */   4,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_EXTMSKtf */
        /* lsp */   31,
        /* len */   6,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_VCMSKtf */
        /* lsp */   15,
        /* len */   16,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_PONSIDtf */
        /* lsp */   8,
        /* len */   7,
    },
    {   /* name     RTL9601B_HSA_DEBUG_DATA_TXHSA0_TRPRSNtf */
        /* lsp */   0,
        /* len */   8,
    },
};
#endif

