// =========================================
// TXPWR.h is auto-generated by tplmt2h.pl.
// =========================================

#ifndef _TXPWR_LMT_92c_H
#define _TXPWR_LMT_92c_H
#define TXPWR_LMT_92c_MAX 2
#include "data_TXPWR_LMT_92c.c"
#include "data_TXPWR_LMT_92c_1.c"
#include "data_TXPWR_LMT_92c_2.c"
unsigned char *data_TXPWR_LMT_92c_array[]={
	NULL,
	data_TXPWR_LMT_92c_1,
	data_TXPWR_LMT_92c_2,
};
unsigned char *data_TXPWR_LMT_92c_array_end[]={
	NULL,
	data_TXPWR_LMT_92c_1+sizeof(data_TXPWR_LMT_92c_1),
	data_TXPWR_LMT_92c_2+sizeof(data_TXPWR_LMT_92c_2),
};
#endif