#!/bin/sh

#
# create essential directory 
#
#mkdir /dev/pts
mount -t tmpfs none /var
mkdir /var/empty
mkdir /var/run
mkdir /var/log
mkdir /var/tmp
mkdir /var/coredump
cp -r /etc /var
mount -t tmpfs none /etc
cp -r /var/etc /
rm -rf /var/etc
touch /var/tmp/log

rm /tmp/log -rf
mkdir /tmp/log/ -p
touch /tmp/log/messages
chmod 777 /tmp/log/messages
#
# mount process
#
#mount -t devpts devpts /dev/pts
mount -t proc proc /proc


#
# insert kernel module if exist
# default path is /lib/modules/X.X.XX/kernel 
#
#cd /lib/modules/X.X.XX/kernel

if test -f "drivers/net/switch/rtcore/rtcore.ko"; then
	insmod drivers/net/switch/rtcore/rtcore.ko
fi

if test -f "drivers/net/switch/rtnic/rtnic.ko"; then
	insmod drivers/net/switch/rtnic/rtnic.ko
fi

if test -f "drivers/net/switch/rtk/rtk.ko"; then
	insmod drivers/net/switch/rtk/rtk.ko
fi

if test -f "/lib/model/model.ko"
then
	insmod /lib/model/model.ko
fi

if test -f "drivers/net/switch/unittest/sdktest.ko"; then
	insmod drivers/net/switch/unittest/sdktest.ko
fi

if test -f "net/switch/rtdrv/rtdrv.ko"; then
	insmod net/switch/rtdrv/rtdrv.ko
fi

cd /
# mount -t jffs2 -o rw,sync /dev/mtdblock5 /mnt
#
# network interface configuration 
#
ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.255.255.0 lo
echo "/var/coredump/core-%e-%p-%t" > /proc/sys/kernel/core_pattern

echo 1 >/proc/sys/net/ipv4/ip_no_pmtu_disc
echo 10 >/proc/sys/net/ipv4/tcp_keepalive_intvl
echo 8 >/proc/sys/net/ipv4/tcp_keepalive_probes
echo 10 >/proc/sys/net/ipv4/tcp_keepalive_time
ulimit -c 4096


ifconfig eth0 0.0.0.0 up
#ifconfig eth0 192.168.0.100

vconfig add eth0 1
ifconfig eth0.1 0.0.0.0

brctl addbr br0
brctl addif br0 eth0.1
#brctl addif br0 eth0
ifconfig br0 up 192.168.0.100 
ifconfig br0 mtu 1496



mkdir -p /etc/snmp

echo "Preparing web pages..."

mkdir -p /tmp/www
if [ -f /www.tar ];then
echo "Found www.tar"
tar xf /www.tar -C /tmp/www
elif [ -f /www.tar.gz ];then
echo "Found www.tar.gz"
tar xf /www.tar.gz -C /tmp/www
fi

mkdir -p /tmp/dev

mknod /tmp/dev/ttyp0 c 3 0
mknod /tmp/dev/ttyp1 c 3 1
mknod /tmp/dev/ttyp2 c 3 2
mknod /tmp/dev/ttyp3 c 3 3
mknod /tmp/dev/ttyp4 c 3 4
mknod /tmp/dev/ttyp5 c 3 5
mknod /tmp/dev/ttyp6 c 3 6
mknod /tmp/dev/ttyp7 c 3 7
mknod /tmp/dev/ttyp8 c 3 8
mknod /tmp/dev/ttyp9 c 3 9
mknod /tmp/dev/ttypa c 3 10
mknod /tmp/dev/ttypb c 3 11
mknod /tmp/dev/ttypc c 3 12
mknod /tmp/dev/ttypd c 3 13
mknod /tmp/dev/ttype c 3 14
mknod /tmp/dev/ttypf c 3 15

mknod /tmp/dev/ptyp0 c 2 0
mknod /tmp/dev/ptyp1 c 2 1
mknod /tmp/dev/ptyp2 c 2 2
mknod /tmp/dev/ptyp3 c 2 3
mknod /tmp/dev/ptyp4 c 2 4
mknod /tmp/dev/ptyp5 c 2 5
mknod /tmp/dev/ptyp6 c 2 6
mknod /tmp/dev/ptyp7 c 2 7
mknod /tmp/dev/ptyp8 c 2 8
mknod /tmp/dev/ptyp9 c 2 9
mknod /tmp/dev/ptypa c 2 10
mknod /tmp/dev/ptypb c 2 11
mknod /tmp/dev/ptypc c 2 12
mknod /tmp/dev/ptypd c 2 13
mknod /tmp/dev/ptype c 2 14
mknod /tmp/dev/ptypf c 2 15

chmod 777 /tmp/dev/* -R

#=================== install modules ============================
#insmod /modules/opl_reg_mmap.ko
#insmod /modules/opl_minte.ko
#insmod /modules/opl_cpuif.ko
#insmod /modules/opl_mem.ko
#insmod /modules/opl_dal_driver.ko
insmod /usr/lib/ifm.ko
#master d&
ponmonitor &

if [ -x /usr/sbin/eponoamd ];then
eponoamd &
fi

if [ -x /usr/sbin/master ];then
master
fi



