/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef CLTCONFIGRTC_H
#define CLTCONFIGRTC_H

#define CLTCONFIGRTCROWSTATUS 1
#define CLTCONFIGRTCYEAR 2
#define CLTCONFIGRTCMONTH 3
#define CLTCONFIGRTCDAY 4
#define CLTCONFIGRTCHOUR 5
#define CLTCONFIGRTCMINUTE 6
#define CLTCONFIGRTCSECOND 7
#define CLTCONFIGRTCWEEK 8



/*
 * function declarations 
 */
void            init_cltConfigRTC(void);
Netsnmp_Node_Handler handle_cltConfigRtcRowStatus;
Netsnmp_Node_Handler handle_cltConfigRtcYear;
Netsnmp_Node_Handler handle_cltConfigRtcMonth;
Netsnmp_Node_Handler handle_cltConfigRtcDay;
Netsnmp_Node_Handler handle_cltConfigRtcHour;
Netsnmp_Node_Handler handle_cltConfigRtcMinute;
Netsnmp_Node_Handler handle_cltConfigRtcSecond;
Netsnmp_Node_Handler handle_cltConfigRtcWeek;


Netsnmp_Node_Handler 	cltConfigRTC_handler;
NetsnmpCacheLoad 		cltConfigRTC_load;
NetsnmpCacheFree 		cltConfigRTC_free;
SNMPAlarmCallback 		cltConfigRTC_commit;

#endif                          /* CLTCONFIGRTC_H */
